### ISSUE TITLE
Releases names are unreadable/non-standard

### ISSUE THREAD

**Issue by Pranav-yadav** [facebook/sapling#141]
> Note: Looks like SemVer isn't being followed
## Current:

[`20221115-080554-34470671`](https://github.com/facebook/sapling/releases/tag/20221115-080554-34470671)

## Expected:
Should use proper [SemVer](https://semver.org/) or more readable release/tag names
Ex.;
```
2.0.2-alpha
major.minor.patch-build
```

## Cause:

https://github.com/facebook/sapling/blob/aaaa8275d7b1e1325ed1283e18bf7a1d0653f46a/.github/workflows/TagIt.yml#L37

**Comment by davide125** [comment]
I would also recommend avoiding dashes, as it causes issues when packaging this for Linux distributions.

**Comment by bolinfest** [comment]
Working on it: https://github.com/facebook/sapling/pull/208

Though I believe we plan to make use of dashes. Example:

```
0.1.20221117-115420-91bf257e
```
