### ISSUE TITLE
Provide a AUR package for Arch Linux users

### ISSUE THREAD

**Issue by overtube** [facebook/sapling#147]
pull them on aur, make pkgbuild pls

**Comment by williewillus** [comment]
I've packaged it (in personal capacity, not as an FB employee) here https://aur.archlinux.org/packages/sapling-scm

**Comment by williewillus** [comment]
There is however an issue with the Makefile that overbuilds, I've filed an issue for it here https://github.com/facebook/sapling/issues/161

**Comment by overtube** [comment]
great,thank!
