### ISSUE TITLE
Reviewstack broken on Firefox

### ISSUE THREAD

**Issue by elliottneilclark** [facebook/sapling#148]
# Repro:
- Using a recent firefox navigate to https://reviewstack.dev/
- Click on Authorize ReviewStack to access GitHub
- Notice the pop up (and accept if this is the first time through)
- Notice that Github has added permissions from the flow
- The browser window now reads: "Failed to delete data. Please close all other instances of ReviewStack, refresh this page, and press Logout again."
- Notice through dev tools that that indexdb and cookies are empty. Local storage has dark mode selection.

# Console Errors:
```
Uncaught (in promise) TypeError: e.databases is not a function
    set gitHubCredentials.ts:154
    n gitHubCredentials.ts:145
    set gitHubCredentials.ts:122
    set recoil@0.7.5-production.js:1
    setNodeValue recoil@0.7.5-production.js:1
    applyAction recoil@0.7.5-production.js:1
    applyActionsToStore recoil@0.7.5-production.js:1
    replaceState recoil@0.7.5-production.js:1
    applyActionsToStore recoil@0.7.5-production.js:1
    queueOrPerformStateUpdate recoil@0.7.5-production.js:1
    setRecoilValue recoil@0.7.5-production.js:1
    useSetRecoilState recoil@0.7.5-production.js:1
    u NetlifyLoginDialog.tsx:29
    lj react-dom@18.2.0-production.js:223
    kj react-dom@18.2.0-production.js:34
    nj react-dom@18.2.0-production.js:34
    gh react-dom@18.2.0-production.js:62
    Xg react-dom@18.2.0-production.js:63
    Ce react-dom@18.2.0-production.js:72
    Tf react-dom@18.2.0-production.js:189
    wg react-dom@18.2.0-production.js:32
    Ce react-dom@18.2.0-production.js:65
    Be react-dom@18.2.0-production.js:47
    Aj react-dom@18.2.0-production.js:46
gitHubCredentials.ts:154:36

```

That line of code reads:

```
const databases = await indexedDB.databases();
```
Going to: https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/databases
Leads us to: https://bugzilla.mozilla.org/show_bug.cgi?id=934640

Seems like the enumeration of databases isn't implemented for FF.

**Comment by bolinfest** [comment]
@elliottneilclark thanks for doing all the research on this!

I just commented on https://bugzilla.mozilla.org/show_bug.cgi?id=934640 because I think Firefox's failure to implement this API should be considered a security concern in addition to a failure to introduce the spec.

I can implement a workaround for ReviewStack, but it's suboptimal.

**Comment by elliottneilclark** [comment]
I completely agree; Clearing the database state doesn't seem like an edge case. Weirdly, https://caniuse.com/?search=IndexDB makes no mention of this either.

Thanks for finding a workaround. I'm looking forward to trying the stack diff life again.
