### ISSUE TITLE
ISL suggests `update --clean`, which doesn't exist

### ISSUE THREAD

**Issue by arxanas** [facebook/sapling#149]
Steps to reproduce:
1. Make some uncommited changes.
2. Try to Goto a different commit in the VS Code ISL.

Actual behavior:

See this message:

> (commit, shelve, update --clean to discard all your changes, or update --merge to merge them)

<img width="825" alt="Screen Shot 2022-11-15 at 15 16 50" src="https://user-images.githubusercontent.com/454057/202045147-622ff854-a2a9-4f55-847b-d6e60d9ef0ba.png">

But `sl update --clean` doesn't work; it looks like `sl goto` is the command instead. Perhaps `update` should be an alias for `goto`? (That's what Jujutsu does IIRC.)

Expected behavior:

All suggested options are valid `sl` commands.

**Comment by yancouto** [comment]
Yes, it's supposed to be `goto` instead of `update`. We will fix the documentation.
