### ISSUE TITLE
Equivalence between `git reset` and `sl hide` is wrong

### ISSUE THREAD

**Issue by arxanas** [facebook/sapling#150]
In the [Git cheat sheet](https://sapling-scm.com/docs/introduction/git-cheat-sheet), the following are equated:

- `git reset --hard COMMIT`
- `sl hide COMMIT`

This is wrong. The former resets *to* `COMMIT`, essentially deleting commits up to but not including `COMMIT`, while `sl hide` will also delete the target commit.

**Comment by luontola** [comment]
Git doesn't really have an operation for deleting commits, unless we're talking about `git gc`. It just hides all commits which are not part of a branch or the current head.
