### ISSUE TITLE
Multiple working tree support

### ISSUE THREAD

**Issue by viveksjain** [facebook/sapling#153]
I like to have multiple working trees checked out simultaneously to be able to read/build them in parallel (and keep build outputs separate etc). Git makes this very easy with worktrees. Is anything similar supported with sapling? I don't see it mentioned in the docs so I assume answer is no, but want to double check (and whether this might be considered on the roadmap).

An equivalent to `git clone --reference` would be a reasonable alternative but that doesn't seem to be supported either.

**Comment by wraithm** [comment]
I confirmed that share works afaict.

**Comment by viveksjain** [comment]
I haven't verified the full functionality but @rbehrends's steps indeed worked for cloning the repo. Good to know that I should search for mercurial behavior rather than git. Thanks!
