### ISSUE TITLE
Submitted stack links to wrong reviewstack URL for forks

### ISSUE THREAD

**Issue by keith** [facebook/sapling#158]
This change https://github.com/facebook/sapling/pull/157 was submitted from changes in my fork of sapling, and the body of the PR links to `https://reviewstack.dev/keith/sapling/pull/157`, which doesn't load. It seems like it should link to `https://reviewstack.dev/facebook/sapling/pull/157` instead

**Comment by bolinfest** [comment]
Thanks for reporting this! We had been keeping mentions of reviewstack.dev out of the public portion of the GitHub codebase up until launch, so this only landed about 9 hours before the blog post went live:

https://github.com/facebook/sapling/commit/c410b866312781cad42f80b1ecdd846bfae360b3

Working on a fix now.

**Comment by bolinfest** [comment]
This isn't an "official" release yet, but these binaries should have the fix for this issue:

https://github.com/facebook/sapling/releases/tag/20221116-131242-1b09643f
