### ISSUE TITLE
Basic Concepts example says `hg prev`, but means `sl prev`?

### ISSUE THREAD

**Issue by luontola** [facebook/sapling#166]
At https://sapling-scm.com/docs/introduction/#basic-concepts the example says:

```
# Go to the previous commit.
$ hg prev
```

But isn't `hg` the CLI for Mercurial? I think the example meant to say `sl prev`.

**Comment by hacker-DOM** [comment]
consider it an easter egg ;-D

**Comment by bolinfest** [comment]
Fixed in aaaa8275d7b1e1325ed1283e18bf7a1d0653f46a.

Fix deployed in https://github.com/facebook/sapling/actions/runs/3481883596
