### ISSUE TITLE
unknown command 'checkout'

### ISSUE THREAD

**Issue by hacker-DOM** [facebook/sapling#168]
The [Basic Concepts](https://sapling-scm.com/docs/introduction/#basic-concepts) section has `sl checkout [PREVIOUS_COMMIT]`

I get 

<img width="669" alt="image" src="https://user-images.githubusercontent.com/18601956/202192083-3c23d1cf-1187-4f27-b7ae-5d695f667dd5.png">

**Comment by mitrandir77** [comment]
The command is supposed to be `sl goto`. I'll fix it the doc soon. Thanks for the report!
