### ISSUE TITLE
How to deep clone a repo?

### ISSUE THREAD

**Issue by neutralinsomniac** [facebook/sapling#176]
I would definitely prefer to ask this sort of question in an IRC channel or something, but this is all I can find. Is it possible to do a deep clone of an existing git repo instead of just cloning the main branch? Or is the intended path to use git to do that, then clone the local git repo with sapling?

**Comment by quark-zju** [comment]
Right now there is no way to clone all branches. If you know the branch names you can do `sl pull -B name` later. Note our commit graph algorithms are optimized with the assumption that your repo does not contain massive amount of branches. So if you have too many (ex. 10000) open branches that can slow things down.
