### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by KyleFin** [facebook/sapling#177]
It would be awesome if Sapling could be generalized to work with other git hosting providers. According to [JetBrains 2020 survey](https://www.jetbrains.com/lp/devecosystem-2020/team-tools/), 77% of respondents regularly use GitHub, 40% GitLab, and 25% BitBucket

I tried to use Sapling with a GitLab repo and it looks like GitHub is a pretty deeply baked in assumption (for URL paths etc).

For example, `sl pr` failed at `url.host == "[github.com](http://github.com/)"` [check](https://github.com/facebook/sapling/blob/89d7a8aac3cb882960ec62bc81ea2c8c17d74de0/eden/scm/edenscm/ext/github/github_repo_util.py#L21)

Aside: Thanks for [open-sourcing](https://engineering.fb.com/2022/11/15/open-source/sapling-source-control-scalable/) Sapling and ReviewStack! I'm really excited for the simplified workflow for managing stacks of small commits!

**Comment by bolinfest** [comment]
When integrating with things like pull requests, we use the GitHub CLI (`gh`) under the hood and GitHub's GraphQL API specifically. Unfortunately, it is not trivial to add support for other Git hosting providers when it comes to the "review" functionality in Sapling.

**Comment by KyleFin** [comment]
Thanks for the quick response! Maybe https://gitlab.com/gitlab-org/cli could provide similar functionality for GitLab, but I can see that would be a non-trivial integration.

**Comment by lf-** [comment]
i think we're talking about a difference analogous to that between git and gitFull.

for what it's worth, the github coupled functionality is largely just stuff on the periphery such as the submit/pr functionality. the actual fetching of repos generally just shells out to git.

**Comment by shk3** [comment]
I'm sorry for reopening this as I just want to provide some ideas we might want to do to balance the such support and Sapling's main roadmap as a SCM. Feel free to close this issue again.

Would it be possible for Sapling CLI to customize the path to `gh`? In this way, people who are using other Git systems can just build scripts / CLI tools that work just like `gh` but under the hood bridge the calls to the corresponding APIs of their own systems. 

Obviously, this would still add some maintenance burden to Sapling, for example, to give a list of queries Sapling CLI uses on GitHub's GraphQL so people don't have to implement the full APIs on their own `gh`, but we might be able to find a way to minimize this burden.

Coming from a company that uses a similar workflow in a monorepo and trunk-based development model, I really appreciate the interoperability Sapling CLI has with GitHub, and I think it could add more impacts to places where they don't use GitHub Enterprise. I would even love to contribute if there is any need!

That being said, I understand the difficulty of maintaining dev infra tools, so here I'm just sharing my random idea. Feel free to close it again if it's not something the team would possibly want to support.
