### ISSUE TITLE
Amend behavior is somewhat confusing, coming from git ecosystem

### ISSUE THREAD

**Issue by MTRNord** [facebook/sapling#178]
Hi I am currently trying this out. First of all this seems like a good approach :)

However, the amend command is confusing to me. 

If I work on two bookmarks without push -> It works as expected and I can amend
If I push bookmark A to A -> A cannot be amended as expected. However B which (looking at github) isnt pushed now also fails with `cannot amend public changesets`

I am wondering if this is expected behavior or if this is not expected. I would have expected that bookmarks somewhat behave like branches until push was executed, as from the user view the commit in bookmark B was not yet made public.

Am I missing some obvious thing here? :) Also if this is expected what is the recommended approach for working on multiple PRs at the same time in a repo where you push them at different times?

**Comment by muirdm** [comment]
Thanks. I'm working on some changes that will, by default, only treat remote/main and remote/master as "public". Currently all remote branches are treated as "public". This will cause all other branches, pushed or not, to be considered "draft" and amendable.

**Comment by MTRNord** [comment]
Ah great. Yeah, that sounds a lot more intuitive 👍

**Comment by cshuaimin** [comment]
@muirdm Hi, I tried HEAD version, but still get the "cannot amend public commits" error.

**Comment by muirdm** [comment]
@cshuaimin What bookmark are you on? As long as the commit isn't an ancestor of remote/main or remote/master, you should be able to amend.

**Comment by cshuaimin** [comment]
I find that it’s using the old version of edenscm package. After a reboot HEAD version works! Thank you.
