### ISSUE TITLE
Watchman integration for status

### ISSUE THREAD

**Issue by viveksjain** [facebook/sapling#184]
The sapling [ISL page](https://sapling-scm.com/docs/addons/isl/) mentions it supports watchman, but as far as I can tell this doesn't apply to other commands, in particular `sl status`. On a large internal repo, I created .watchmanconfig but `status` still takes 9 secs (and I confirmed with `watchman watch-list` that there is no watch on the repo, it only gets created after `sl web`).

It would be great if sapling integrated something like https://git-scm.com/docs/git-fsmonitor--daemon to speed up status. (I presume the virtual FS has its own implementation which is not O(# files in repo), but until that's available or for those who want to keep things local.)

**Comment by quark-zju** [comment]
If you run `sl status --debug` does it say anything about watchman?

**Comment by viveksjain** [comment]
Ah seems this is supposed to already be supported? Let me know how to debug it further
```
$ sl status --debug
watchman sockpath is set as /opt/facebook/watchman/var/run/watchman/vivek.jain-state/sock
starting pager for command 'status'
```
This is not the correct path based on `watchman get-sockname`. From the code I see I can add
```
[fsmonitor]
sockpath = /opt/homebrew/var/run/watchman/vivek.jain-state/sock
```
to the config. After doing so, `sl status --debug` shows correct path but still is just as slow, and `watchman watch-list` still doesn't include the repo.

**Comment by quark-zju** [comment]
Could you share the output of this command run within 15 minutes after a slow `sl status`?

    sl blackbox --pattern '["or",{"watchman":"_"},{"fsmonitor":"_"}]'

**Comment by viveksjain** [comment]
The output of that command is completely empty (ran both `sl status --debug` and `sl status` before it)

**Comment by viveksjain** [comment]
If it matters I have enabled the share extension. Removing `share =` from the config file doesn't seem to make any difference though.

**Comment by quark-zju** [comment]
If you run:

     SL_AUTOMATION=1 sl debugrefreshwatchmanclock

would it print anything interesting?

**Comment by viveksjain** [comment]
```
$ SL_AUTOMATION=1 sl debugrefreshwatchmanclock
abort: cannot watch repo: 'physicalfilesystem' object has no attribute '_watchmanclient'
```

**Comment by quark-zju** [comment]
Could you share some more information?

- Is your OS Linux or macOS?
- What's the output of `sl debugextensions | grep -E '(fsmonitor|hgevents)'`?

**Comment by quark-zju** [comment]
Hi, @viveksjain We think the latest release solves this issue. Could you try if it works for you?

**Comment by viveksjain** [comment]
It works great! When warmed up it's < 100ms now 🎉 . Thanks!
