### ISSUE TITLE
[ReviewStack] ReviewStack not working for private repository

### ISSUE THREAD

**Issue by theskcd** [facebook/sapling#188]
Hi!
Really excited about sapling and reviewstack and thanks for open sourcing this.
I was trying to onboard our repository and when opening review stack I am greeted with a blank page. Looking at the network tab I see 404 on the request `https://reviewstack.dev/{repository}/pull/2460`
Attaching the image below, do let me know if you need more data from me to debug this.

If this is not the right place to send issues for ReviewStack, I can move it to the right place.
Thanks for making these!

![Screenshot 2022-11-17 at 10 02 13](https://user-images.githubusercontent.com/10356126/202416923-3ac99eb7-6f71-4081-b4dd-e38736550984.png)

**Comment by bolinfest** [comment]
@theskcd Thanks for reporting! Questions:

- Is ReviewStack working for you with public repos?
- This is "regular" GitHub, not GitHub Enterprise, correct?
- Is it possible that the associated GitHub organization (it looks like `conversionpattern` from the screenshot) has blocked OAuth apps? This feels like the most likely issue, though I thought that we got an error message explaining that in the HTTP response when that was the case.

**Comment by theskcd** [comment]
> Is ReviewStack working for you with public repos?

yeah, I had some older commits which I can see on ReviewStack

> This is "regular" GitHub, not GitHub Enterprise, correct?

Ohhh I think its enterprise (is that not supported?)

> Is it possible that the associated GitHub organization (it looks like conversionpattern from the screenshot) has blocked OAuth apps?

I will need to check this in my settings, let me have a look and get back to you with that.

Thanks for helping with the issue!

**Comment by theskcd** [comment]
> Is it possible that the associated GitHub organization (it looks like conversionpattern from the screenshot) has blocked OAuth apps? 

Hmm but reviewstack asks for permission when trying to open the link (and I did grant the permission at the time). I was hoping that would fix the issue but maybe not?

**Comment by bolinfest** [comment]
GHE is not supported at the moment. Let me see what I can do. Allegedly, I can set up a trial version of GHE to test this out.

**Comment by theskcd** [comment]
That would be great! Do let me know if you need anything from me to help with the testing. Thanks again for the help, much appreciated!

**Comment by bolinfest** [comment]
The new version of https://reviewstack.dev/ is deployed, which now includes instructions for logging in with a GitHub Enterprise account!
