### ISSUE TITLE
Failed `sl push` shows commit as successfully pushed

### ISSUE THREAD

**Issue by lfousseaq** [facebook/sapling#189]
This is sapling built from `64e95e85e047c6fb27a31928ed24fbddb9b6bca9`. Steps to reproduce:

1. Clone a repository with a protected `main` branch.
2. Do a trivial change and `sl commit`.
3. `sl push`

The `push` failed with:
```
remote: error: GH006: Protected branch update failed for refs/heads/main.
```

But the output of `sl` shows the commit as being part of `remote/main`:

```
$ sl
@  7ac22d4fa  33 seconds ago  lfousse  remote/main
│  Test sapling bug.
~
```

The local client is now in an inconsistent state (`sl pr` refuses to create a PR on GitHub for a commit that's "already upstream").

**Comment by neutralinsomniac** [comment]
I ran into this as well trying to push to a repo I didn't have permissions to push to. The incorrect local state can at least be fixed with an `sl pull`.
