### ISSUE TITLE
ReviewStack versions are confusing?

### ISSUE THREAD

**Issue by francois** [facebook/sapling#192]
I made a stack with 2 commits. I pulled from master, rebased against it, then made a change on the 2nd commit.

<img width="1460" alt="" src="https://user-images.githubusercontent.com/247/202532869-88aab2c2-b70f-4a34-8ad1-0833f8320518.png">

When viewing ReviewStack on the 2nd PR, on the sidebar to the right, I can see 3 versions, but the Version select at the top still says "V1". The diff section shows code as it existed at V1, not V3.

Am I doing something wrong?

**Comment by bolinfest** [comment]
@francois I definitely have to clean up somethings here. Out of curiosity, did you use `sl pr` or `sl ghstack`?

**Comment by francois** [comment]
I used sl pr.

**Comment by kalaracey** [comment]
Possibly related: https://github.com/facebook/sapling/issues/587

**Comment by ahornby** [comment]
as mentioned on https://github.com/facebook/sapling/issues/587 I'm seeing similar, reviewstack versions drop down only has 1 entry despite 4 versions in sidebar and only showing the v1 changes: https://reviewstack.dev/benbrittain/buckle/pull/10 The prs are made and updated with sl pr submit using the gh backed. Sapling version is 0.2.20230523-092610+f12b7eee, gh version 2.31.0 (2023-06-20)

**Comment by ahornby** [comment]
published a couple of PRs that seemed to fix this for me.   reviewstack had the version related functions disabled for sapling prs
