### ISSUE TITLE
Unexpected commit author in commit graph

### ISSUE THREAD

**Issue by alive** [facebook/sapling#194]
When running `sl`, we get output like:

```
@  aa9a556dd  31 minutes ago emailuser
│  my first commit with sapling
```

When `sl config ui.username` is
```
sl config ui.username
alive <emailuser@example.com>
```

Can anyone weigh in on why this is? I would expect:
```
@  aa9a556dd  31 minutes ago  alive
│  my first commit with sapling
```
If both a username (alive) and an email (<emailuser@example.com>) are provided as `ui.username`

**Comment by bolinfest** [comment]
Consider the example from https://sapling-scm.com/docs/introduction/getting-started/ (which is consistent with the Git equivalent):

```
sl config --user ui.username "Alyssa P. Hacker <alyssa@example.com>"
```

Many/most people put their full name followed by their email address (which has a username and a domain). Within an organization like Meta:

1. "Real names" are long and are usually unique, but not guaranteed to be globally unique within the company.
2. The domain is the same for everyone (`meta.com`) and are therefore uninteresting.
3. Usernames are bounded in length (often short) and are globally unique within the company.

So the default behavior makes sense within a company. Maybe not in other settings, but you can override the way the user is displayed in the smartlog by redefining the `sl_user` part of the template as follows:

```
sl config -u templatealias.sl_user "'{label(\"sl.user\", author)}'"
```

You can see the current default definition of this template here:

https://github.com/facebook/sapling/blob/a10c8654ccdd12c2d091e263e056957d56a4433b/eden/scm/lib/config/parser/src/opensource.rs#L273
