### ISSUE TITLE
How to add git remote (for interfacing with Heroku)

### ISSUE THREAD

**Issue by jasonsbrooks** [facebook/sapling#196]
Our codebase is powered by Git and hosted on GitHub. We use Heroku for hosting our service. The recommended way of interfacing/pushing code to Heroku is by adding a git remote for Heroku:

`git remote add heroku git@heroku.com:app-name.git`

and then deploying it to Heroku via

`git push heroku`

What is the recommended way of interacting with remote destinations in Sapling? According to the [documentation](https://sapling-scm.com/docs/introduction/git-cheat-sheet), you can add a remote using `sl path --add REMOTE URL`, but I can't seem to then push to that remote via `sl push --to BRANCH`. Running the push just pushes a new branch with that name to my git repo.

**Comment by muirdm** [comment]
@jasonsbrooks  Did you try `sl push heroku --to BRANCH` (assuming you named the remote "heroku")? The `[DEST]` positional argument can be the name of a "path".

**Comment by quark-zju** [comment]
If you run into issues, try using ssh instead of scp-like URL:

     ssh://git@heroku.com/app-name.git

**Comment by vegerot** [comment]
I have the same question.

I frequently contribute to open source projects.  Normally I will have 2 remotes: `upstream` and `github`, when I push a change I'll do `git push github @:refs/heads/mybranch` and when I want to get the latest changes I'll do `git fetch upstream && git rebase refs/remotes/upstream/main`.

What is the equivalent to this in Sapling?

**Comment by vegerot** [comment]
I figured it out.  Something VERY confusing about sapling is that ssh URLs use `/` instead of `:` to separate the host from the path.

I accidentally did

```sh
sl path --add remote ssh://git@github.com:my/repo.git
```

instead of 

```sh
sl path --add remote ssh://git@github.com/my/repo.git
```
.

IMO this is confusing and bound to lead to confused users.  Especially because when you click the "Clone" button on GitHub it gives you the former template
