### ISSUE TITLE
Maybe it's a april fool's joking!

### ISSUE THREAD

**Issue by gnu4cn** [facebook/sapling#200]
You Meta guys opened a code repository system - sapling, but it's been hosted on GitHub, you lost your brains? is this a big joking?

**Comment by quark-zju** [comment]
Note the Git repo format and the Git client are two separate things.  We target the Git format first, since that's the mostly widely used format so more people can benefit from our usability and scalability work. The source of the truth of Sapling code is not Git and this Git repo is a mirror.

**Comment by muirdm** [comment]
Thank you for your interest.

What we've released is primarily a source control client compatible with Git, so hosting on GitHub seems appropriate.
