### ISSUE TITLE
Restart sl daemon after ulimit changes

### ISSUE THREAD

**Issue by nataliejameson** [facebook/sapling#204]
I hadn't set the open files limit with ulimit before running an `sl` clone. After running the clone, I hit the open file limit issue that is mentioned in the installation docs. So, I set ulimit in my .bash_profile, but was still running into issues. Turns out I had forgotten to kill the `sl` daemon that was started with the old limits. 

Is there any way we can detect that and either restart the daemon gracefully, or at least warn about it? It seems like it might be a bit non-obvious that there even is a daemon running, so it could be an annoyance. Maybe even just making it an `sl doctor` feature would be enough.

**Comment by neutralinsomniac** [comment]
I *just* ran into this issue this morning. Thank you for submitting the issue; I had no idea a daemon was even involved and was very confused as to why my new ulimit wasn't seeming to take effect.

**Comment by bolinfest** [comment]
@wez this probably explains what you ran into?

**Comment by wez** [comment]
@bolinfest ah! I'd forgotten about chg, yeah, that makes sense
