### ISSUE TITLE
The github extension breaks some commands for non-github repos

### ISSUE THREAD

**Issue by rbehrends** [facebook/sapling#229]
This affects especially the smartlog and pull subcommands. `sl pull` is further affected in that disabling the github extension also results in an `unknown command 'debugprmarker'` error, unless you also disable the `post-pull.prmarker` hook.

Steps to reproduce:

```
$ sl clone https://gitlab.com/gitlab-examples/docker
$ cd docker
$ sl sl
abort: Either gitlab.com is not a GitHub Enterprise hostname or you are not logged in.
Authenticate using the GitHub CLI: `gh auth login --git-protocol https --hostname gitlab.com`
$ sl pull
pulling from https://gitlab.com/gitlab-examples/docker
abort: Either gitlab.com is not a GitHub Enterprise hostname or you are not logged in.
Authenticate using the GitHub CLI: `gh auth login --git-protocol https --hostname gitlab.com`
warning: post-pull.prmarker hook exited with status 255
$ printf '[extensions]\ngithub=!\n' >>$(sl configfile -l)
$ sl sl
@  29b7d9317  2016-04-15 11:25  ayufan  remote/master
│  initial commit
~
$ sl pull
pulling from https://gitlab.com/gitlab-examples/docker
unknown command 'debugprmarker'
(use 'sl help' to get help)
warning: post-pull.prmarker hook exited with status 255
sl --config hooks.post-pull.prmarker= pull
pulling from https://gitlab.com/gitlab-examples/docker
```

(This is based on the most recent sapling release, I think some earlier releases did not exhibit this behavior.)

**Comment by bolinfest** [comment]
@rbehrends thanks for reporting: this is a hi-pri issue!

**Comment by zzl0** [comment]
@rbehrends thanks for reporting. Currently, `debugprmarker` is part of 'github' extension for automatically hiding merged PRs. You disable `post-pull.prmarker` hook as a temporary fix to unblock youself. I am working on this issue.

**Comment by zzl0** [comment]
For anyone met this issue, we have a fix for this bug and it will be included in next release. While waiting for the new release, you can unblock yourself by disable `github` and `prmarker` extension/hook.

```
$ sl config -e

# to disable `github` extension
[extensions]
github=!

# to disable `prmarker` hook
[hooks]
post-pull.prmarker=
```

**Comment by zzl0** [comment]
fixed in the new release.
