### ISSUE TITLE
Reverse order of branch names

### ISSUE THREAD

**Issue by sheremetyev** [facebook/sapling#231]
When submitting multiple PRs from Sapling CLI, branches on GitHub are created in reverse order.

Example: submitted three PRs and got:
- https://github.com/sheremetyev/sapling-test-1/pull/1 has branch name "pr3"
- https://github.com/sheremetyev/sapling-test-1/pull/3 has branch name "pr1"

---

Steps to reproduce:

1) create a new repository on GitHub

2) clone repository
```
$ sl clone https://github.com/sheremetyev/sapling-test-1.git
$ cd sapling-test-1
```

3) create several commits
```
$ echo foo > foo.txt ; sl add foo.txt ; sl ci -m 'adding foo'
$ echo bar > bar.txt ; sl add bar.txt ; sl ci -m 'adding bar'
$ echo baz > baz.txt ; sl add baz.txt ; sl ci -m 'adding baz'
```

4) submit multiple PRs at once
```
$ sl pr
```

5) check names of branches in the created PRs on GitHub

Expected: branch names suffixes match PR numbers
Actual: bottommost PRs in the stack has lowest PR number but highest branch number

---

Environment: macOS arm64

Sapling installed as described at https://sapling-scm.com/docs/introduction/installation#apple-silicon-arm64

```
$ sl --version
Sapling 0.1.20221118-210929-cfbb68aa
```

**Comment by bolinfest** [comment]
Thanks for filing! I discovered on Friday that I regressed this recently. Will fix!

**Comment by bolinfest** [comment]
We plan to do a new release this morning with this fix!
