### ISSUE TITLE
sl help config.files is very outdated

### ISSUE THREAD

**Issue by lf-** [facebook/sapling#268]
It references `.hgrc` in several places and seems to be entirely inaccurate based on my reading of the README, at least.

**Comment by muirdm** [comment]
I cut out some outdated content in ea975582515db81c6ccddf986630a568ac4d613f. I think it's mostly okay now, except the last part isn't true in all cases for git repos. @lf- Are you satisfied w/ the updated content of "sl help config.files"?

**Comment by lf-** [comment]
This looks much better, thanks.
