### ISSUE TITLE
versioning scheme

### ISSUE THREAD

**Issue by shiena** [facebook/sapling#271]
#208 shows `VERSION-%Y%m%d-%H%M%S-HASH` but actually [tag-name.sh](https://github.com/facebook/sapling/blob/main/ci/tag-name.sh) is `VERSION.%Y%m%d-%H%M%S-HASH` outputting. Which is correct?

**Comment by sggutier** [comment]
Oh, that's a typo in the PR. [The versioning scheme](https://github.com/facebook/sapling/blob/main/ci/tag-name.sh) [is `VERSION.%Y%m%d-%H%M%S-HASH`](https://github.com/facebook/sapling/releases/tag/0.1.20221118-210929-cfbb68aa).
