### ISSUE TITLE
Draft PRs

### ISSUE THREAD

**Issue by spence-novata** [facebook/sapling#288]
It would be handy if all the GitHub PRs except the bottom one (ie the next one to be merged in) were put in draft state to prevent accidental merging. Then as each is merged the next one can be move into a "ready for review state"

I don't know if this is the right place to place this, I couldn't see any info on the best place for feature requests

**Comment by bolinfest** [comment]
https://github.com/facebook/sapling/commit/6e9c3d7a6671839601c8064f0ae5fc2f3e2d361c adds a `--draft` flag, so that should be available in the next release. I'm in the midst of doing a bunch of cleanup around `sl or submit` in response to GitHub issues like this!

**Comment by bolinfest** [comment]
The `--draft` flag made it into this release: https://github.com/facebook/sapling/releases/tag/0.2.20221222-152408-ha6a66d09
