### ISSUE TITLE
`sl graft` does not keep dates by default, contrary to its documentation

### ISSUE THREAD

**Issue by mstone** [facebook/sapling#299]
### Issue

The [documentation](https://github.com/facebook/sapling/blob/main/eden/scm/edenscm/commands/__init__.py#L2395-L2396) for `sl graft` claims that "...[b]y default, graft will also copy user, date, and description from the source commits..." but this is not true in my testing; instead, today, `sl graft` does not copy dates unless this [configuration check](https://github.com/facebook/sapling/blob/main/eden/scm/edenscm/ext/tweakdefaults.py#L597) is made to return true by configuring 

```
[tweakdefaults]
graftkeepdate = True
```

**Comment by mstone** [comment]
(One other method record for historical/future reference about the debugging process I used to track this down for any sapling non-experts like me who may nevertheless encounter this issue or need to deal with a similar surprise:

To debug this, I first found and read the source for `sl graft` and then used the built-in debugger like so:

```bash
sl undo; sl graft -v --debugger 'local/main % .'
import edenscm.commands
b edenscm.commands._dograft
c
p opts['date']
```

to perform a test graft, then checked that the relevant 'date' option was being set when I expected it not to be since I had not set it via the CLI, then I got lucky by noticing a suspicious-looking line four frames up in the backtrace:

```
  .../lib/python3.8/site-packages/edenscm/ext/tweakdefaults.py(599)graftcmd()
    598         opts["date"] = currentdate()
--> 599     return orig(ui, repo, *revs, **opts)
    600 
```

that proved to be the unwanted assignment to `opts["date"]` that I linked to above.)

**Comment by zzl0** [comment]
@mstone thanks for reporting the issue. The documentation is outdated, we changed the default behavior in [this commit](https://github.com/facebook/sapling/commit/d5c12360a4bfb5613b70c4ae36e66fe30c508415)

**Comment by mstone** [comment]
Makes sense and looks good, thanks!
