### ISSUE TITLE
The most recent release for Apple Silicon does not start

### ISSUE THREAD

**Issue by rbehrends** [facebook/sapling#315]
Symptoms (running on a Mac M1 mini):

```
$ sl
dyld[1196]: symbol not found in flat namespace (_PyBool_Type)
zsh: abort      sl
```

There is no daemon running. This is with `sapling_0.1.20221208-212056-r520df27a.arm64_monterey.bottle.tar.gz`.

The Intel version does not have that problem, and can apparently also (via Rosetta) be used on M1 Macs as a workaround.

**Comment by bolinfest** [comment]
Yikes, perhaps this is due to https://github.com/facebook/sapling/commit/81685da429b7245f939792506d2b3568db1a19fe

**Comment by bolinfest** [comment]
Thanks for reporting! I just changed "Latest" to the previous release for now.

**Comment by bolinfest** [comment]
Good news! https://github.com/facebook/sapling/commit/a443a6cfefa51efaf7e69f3943cf53ca276b4ff3 should fix this, though I am still waiting for some other commits to make it through our build pipeline. Once they are exported to GitHub, I'll kick off a new release build.

**Comment by bolinfest** [comment]
@rbehrends (and others), here is the new release candidate with the fixes:

https://github.com/facebook/sapling/releases/tag/0.1.20221212-142634-r7ae28228

Please confirm that this looks good to you!

**Comment by bolinfest** [comment]
Incidentally, I had to run `sl --kill-chg-daemon` to get things working after the `brew install`. @quark-zju is investigating why `sl` did not detect the version change automatically.

**Comment by bolinfest** [comment]
RC published to latest and the website has been updated: closing and thanks for your patience!
