### ISSUE TITLE
There is no vim editor's plugin for sapling-scm support.

### ISSUE THREAD

**Issue by gnu4cn** [facebook/sapling#325]
For the old git-scm, there are dozens of plugins available. But there is no vim plugin for sapling-scm.

**Comment by vsiles** [comment]
I don't know how compatible it is, but I'm using https://github.com/ludovicchabant/vim-lawrencium with hg and vim-fugitive with git

**Comment by muirdm** [comment]
Thanks for your interest. Apart from the VS Code extension and the included Interactive Smartlog web app, we don't have plans to provide editor specific user experiences. A community driven project would make sense.

I'm not a Vim user, but probably an existing Mercurial plugin could be lightly modified to provide value, such as logging/annotating a file. Creating a more featureful plugin would take more work, but could use the Interactive Smartlog code/design as reference.

If you get something working please report back. We can maintain recommendations in our documentation for editor specific integrations.
