### ISSUE TITLE
Production blobstore storage metadata and storage backends (e.g. something like S3) with mvsqlite

### ISSUE THREAD

**Issue by fire** [facebook/sapling#326]
The readme for mononoke mentions you currently use sqlite.

mvsqlite is a distributed externally consistent rdms based on sqlite and FoundationDB.

It would be cool to see if these two projects can interoperate and become more robust.

## References

* https://github.com/losfair/mvsqlite
* https://github.com/facebook/sapling/blob/main/eden/mononoke/README.md

**Comment by muirdm** [comment]
I believe sqlite is a stopgap until we do a supported release of Mononoke with production database support.

/cc @markbt

**Comment by fire** [comment]
@losfair I'm curious about your thoughts?

**Comment by ahornby** [comment]
done in https://github.com/facebook/sapling/commit/c5edcd62fcf187b4f56e6cf82eb2147ecaa227ba

**Comment by fire** [comment]
Thanks!
