### ISSUE TITLE
Installation instructions also clobber max file size, not just open file limit

### ISSUE THREAD

**Issue by mhlakhani** [facebook/sapling#353]
Hi!

The [installation instructions](https://sapling-scm.com/docs/introduction/installation) mention this:

```
echo "ulimit -n 1048576 1048576" >> ~/.bash_profile
echo "ulimit -n 1048576 1048576" >> ~/.zshrc
```

A few weeks after running this I ran into an issue editing files > 512MB: programs would randomly error with "file size limit exceeded" because 1048576 * 512 bytes per block (the default on my system) exceeded the limit. I expect this isn't desirable.

Can the instructions somehow be amended to only affect the # of open files, and not affect the file size limit? 

For reference, `ulimit -n 1048576 unlimited` worked for me but I expect `unlimited` might not be a good default for everyone else.

**Comment by zzl0** [comment]
@mhlakhani thanks for posting the issue, 

Yes, the `ulimit -n` is for setting the number of open files. Could you run`ulimit -a` and check what's the value of 'file size' on your machine?

For example, below is the output of 'ulimit -a' on my Mac:
```
$ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       5568
-n: file descriptors                1048576
```

**Comment by mhlakhani** [comment]
@zzl0  right now it's unlimited because I had to change it.

Basically if I run `ulimit -n 1048576 1048576` which the docs suggest and then run `ulimit -a` I get:

```
➜  ~ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       4000
-n: file descriptors                1048576
➜  ~ ulimit -n 1048576 1048576
➜  ~ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              1048576
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       4000
-n: file descriptors                1048576
```

This means the filesize is now also limited which isn't great.

**Comment by zzl0** [comment]
Thanks, the command should be `ulimit -n 1048576`.

> ulimit -n 1048576 1048576

the issue here is because the second argument does not have an option, then -f is assumed [1].

[1] bash ulimit.def: https://github.com/bminor/bash/blob/ec8113b9861375e4e17b3307372569d429dec814/builtins/ulimit.def#L64

**Comment by mhlakhani** [comment]
thanks! I'll send a PR

**Comment by zzl0** [comment]
I forgot to mention that I had an internal PR that is waiting for review, but I would prefer your PR, thanks for contributing to Sapling.
