### ISSUE TITLE
Unable to run 'sl web' on Mac

### ISSUE THREAD

**Issue by PKlumpp** [facebook/sapling#362]
Hi folks,

I am running macOS Ventura 13.0.1, Sapling 0.2.20221222-152408, and tried to integrate sapling in my VS Code distribution. This worked, but I would always receive an error message when trying to access the interactive smart log. It says:
`Something went wrong
Cannot read properties of undefined (reading 'Commit Info')
TypeError: Cannot read properties of undefined (reading 'Commit Info')
    at b (https://file+.vscode-resource.vscode-cdn.net/Users/philipp/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js:1481:237140)
    at v (https://file+.vscode-resource.vscode-cdn.net/Users/philipp/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js:1481:236983)
    at Ss (https://file+.vscode-resource.vscode-cdn.net/Users/philipp/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js:1481:73686)
    at xl (https://file+.vscode-resource.vscode-cdn.net/Users/philipp/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js:1481:130645)
    at yc (https://file+.vscode-resource.vscode-cdn.net/Users/philipp/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js:1481:119627)
    at vc (https://file+.vscode-resource.vscode-cdn.net/Users/philipp/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js:1481:119555)
    at gc (https://file+.vscode-resource.vscode-cdn.net/Users/philipp/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js:1481:119418)
    at oc (https://file+.vscode-resource.vscode-cdn.net/Users/philipp/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js:1481:116225)
    at ic (https://file+.vscode-resource.vscode-cdn.net/Users/philipp/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js:1481:114780)
    at C (https://file+.vscode-resource.vscode-cdn.net/Users/philipp/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js:1481:223766)`

When running sapling via CLI, it fails as well with a different error:
`(node:8590) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'mkdtemp' of undefined
    at /usr/local/Cellar/sapling/HEAD-e322323/lib/python3.10/site-packages/edenscm-isl/isl-server/dist/run-proxy.js:1:9037
    at Generator.next (<anonymous>)
    at s (/usr/local/Cellar/sapling/HEAD-e322323/lib/python3.10/site-packages/edenscm-isl/isl-server/dist/run-proxy.js:1:3499)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
(node:8590) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8590) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I am not sure what I'm missing, anything else is working fine, but the ISL appears to be broken for me.

**Comment by bolinfest** [comment]
What does `node --version` say and how did you install Sapling?

**Comment by PKlumpp** [comment]
I am running node v9.4.0, and I installed sapling via homebrew `brew install sapling`. The VS Code extension was just installed via the extensions page.

**Comment by bolinfest** [comment]
That is a *very* old version of Node and is the source of your issue. Our Brew formula specifies Node as a dependency, but I guess you have some other Node that is ahead of it on the PATH. What does `which -a node` report?

We can try to detect old Node versions on our side and have a proper error message.

**Comment by PKlumpp** [comment]
Good point, the node version on my PATH was not the one I had installed with brew. Removing the outdated version fixed `sl web` and I can see the smartlog in my browser, however, I still face the same issue (`TypeError: Cannot read properties of undefined (reading 'Commit Info')`) in VS Code.
Thanks!

**Comment by bolinfest** [comment]
Have you closed and reopened VS Code since you fixed your PATH issue?

**Comment by PKlumpp** [comment]
Yes I did. I cannot really make much sense of the message either. At first I thought it was not in a version-controlled folder, but that was not the case, as all other commands appear to work fine.

**Comment by bolinfest** [comment]
Hmm, I am on:

- macOS 12.6.1
- `sl version` is `Sapling 0.2.20221222-152408`
- `node --version` is `v16.15.1`
- `code --version` is `1.74.1 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a x64`
- and `v0.1.7` for the Sapling VS Code extension

and Interactive Smartlog works fine for me inside VS Code. It's particularly strange to me that `sl web` works because the most recent versions of the VS Code extension and the CLI were cut from almost the same commit, so there were not many changes between the two.

My only other guess (without trying to use the sourcemap to demangle the stack trace) is if the terminal that had the old `$PATH` was used to launch VS Code and somehow the `$PATH` was still cached or something like that, though even so, the trace suggests a logical error rather than having a Node version that was too old. (The other issue was more obvious because it was a Node version that didn't have `fs.mkdtemp` or whatever.)

**Comment by bolinfest** [comment]
@PKlumpp is your language set to something other than English? I think that `'Commit Info'` is a key in our translations table. Also, I installed [this source map CLI](https://www.npmjs.com/package/source-map-cli) and ran:

```
$ source-map resolve  ~/.vscode/extensions/meta.sapling-scm-0.1.7/dist/webview/isl.js.map 1481 237140
Maps to ../../isl/src/i18n/index.tsx:139:29 (i18nKeyOrEnText)

      langs[currentLanguage][i18nKeyOrEnText] ?? langs.en[i18nKeyOrEnText] ?? i18nKeyOrEnText;
                             ^
```

**Comment by bolinfest** [comment]
Indeed, this does not look like it will do the right thing if `currentLanguage` is not in `langs`:

https://github.com/facebook/sapling/blob/eda170e8b49ab6d280d4470823475d717af154fd/addons/isl/src/i18n/index.tsx#L139

**Comment by bolinfest** [comment]
Hmm, that PR might not be sufficient, as this looks like it also might not defend against a missing language:

https://github.com/facebook/sapling/blob/eda170e8b49ab6d280d4470823475d717af154fd/addons/isl/src/i18n/index.tsx#L172-L176

**Comment by bolinfest** [comment]
Likely the only reason we haven't hit this is because the first translation that was evaluated did not have `count` set, avoiding the consequent of this `if` block:

https://github.com/facebook/sapling/blob/eda170e8b49ab6d280d4470823475d717af154fd/addons/isl/src/i18n/index.tsx#L127-L136

**Comment by PKlumpp** [comment]
My language is set to English (which was the default, and I never changed that). I can also open a terminal from inside VS Code and run sl web from there, works fine. You provided your `code --version`, what exactly does this refer to? `code` appears not to be installed / on my $PATH

**Comment by bolinfest** [comment]
Hmm, I will say this: if I choose **Configure Display Language**

**Comment by bolinfest** [comment]
`code` is the CLI that you can use to launch VS Code. I think you may have to choose **Shell Command: Install 'code' command in PATH command** from the command palette to set this up, though I though VS Code also prompts you to do this upon initial install.

**Comment by bolinfest** [comment]
@PKlumpp I just published v0.1.8 of the VS Code extension with the fixes linked to this PR. Please install it and report back on whether it fixes your issues! If nothing else, at least you should get a *new* error message, though I expect things will be working now.

**Comment by PKlumpp** [comment]
Great work @bolinfest, the latest version of the VS Code plugin fixed the crashes.

**Comment by bolinfest** [comment]
@PKlumpp wonderful: glad to hear it!
