### ISSUE TITLE
🐛 `sl clone` silently fails for some repositories

### ISSUE THREAD

**Issue by vegerot** [facebook/sapling#375]
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/5297725/210120851-65d67d35-17b9-4f72-a921-edf672bd9c4d.png">

Background: I am trying to clone https://github.com/cli/cli (in order to build it from source to help debug #350 )

Steps to reproduce:
1. `sl clone git@github.com:cli/cli.git`
2. `ls cli`

Expected output:
- files in https://github.com/cli/cli (`README.md`, etc.)

Actual output: 
- nothing 🙈

Other sanity-testing checks:
- `git clone` works
- `sl clone` another repo works
- `gh repo clone` works

## versions and configs
- sl: built from source on 97ec2f93b (`sl version` reports `Sapling 4.4.2`)
- git: 2.39.0
- gh: 2.21.1
- os: macOS 13.1 (Ventura)

```sh
❯ sl config
alias.commit=commit --verbose
alias.sst=!$HG status && $HG ssl
merge-tools.nvimDiff.args=-d $local $other $base -c 'redraw | echomsg "hg merge conflict, type \":cq\" to abort vimdiff"'
merge-tools.nvimDiff.executable=/usr/local/bin/nvim
merge-tools.nvimDiff.priority=100
ui.editor=nvim
ui.username=Max 👨🏽‍💻 Coplan <mchcopl@gmail.com>
```

```sh
git config --list

credential.helper=osxkeychain
alias.s=!{ git for-each-ref --sort=-committerdate --format='%(refname)' refs/heads/ refs/remotes/$(git remote || printf origin)|sed -e 's-refs/heads/--'| sed -e "s-refs/remotes/$(git remote || printf origin)/--" & printf 'develop
main
master
'; } | uniq | grep -i -m1 --color=never $1 | xargs -I {} sh -c " echo {}; git switch {}"
alias.sf=!git switch $(git for-each-ref --sort=-committerdate --format='%(refname)' refs/heads/ refs/remotes/$(git remote || printf origin)/|sed -e 's-refs/heads/--'| sed -e "s-refs/remotes/$(git remote || printf origin)/--" | uniq | fzf) $@
alias.fr=!git fetch $(git remote | head) && git rebase
alias.frm=!git fetch $(git remote | head) && git rebase $(git remote | head)/main
alias.fru=!git fetch upstream && git rebase upstream/main
alias.cw=commit --fixup=wip
core.pager=${_GIT_CONTRIB:-/usr/local/share/git-core/contrib}/diff-highlight/diff-highlight | $PAGER
color.branch.current=yellow reverse
color.branch.local=yellow
color.branch.remote=green
color.diff.meta=yellow bold
color.diff.frag=magenta bold
color.status.added=green bold
color.status.changed=red bold strike
color.status.untracked=cyan
color.status.branch=yellow bold ul
commit.verbose=true
interactive.difffilter=$_GIT_CONTRIB/diff-highlight/diff-highlight | $PAGER
rebase.instructionformat=(%al) %s
pull.fastforward=true
pull.ff=only
pull.rebase=true
user.email=Max.Coplan@walmart.com
user.name=Max 👨🏽‍💻 Coplan
help.autocorrect=1
url.git@github.com:.insteadof=https://github.com/
```

```sh
❯ gh config list
git_protocol=ssh
editor=
prompt=enabled
pager=
http_unix_socket=
browser=
```

Please let me know what other info you need 🙂 

Happy New Year 🎆 🎊 🎈

**Comment by bolinfest** [comment]
Hmm, that `url.git@github.com:.insteadof=https://github.com/` line in your `git config --list` seems interesting? I just tried `sl clone git@github.com:cli/cli.git` with the latest Sapling release on Windows, but it failed with a more straightforward error:

```
abort: git command failed with exit code 128
  git "--git-dir=C:\Users\bolin\src\cli\.sl/store\git" ls-remote --refs "ssh://git@github.com/cli/cli.git" refs/heads/main refs/heads/master
    Host key verification failed.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

C:\Users\bolin\src>git --version
git version 2.36.1.windows.1
```

Though then I tried `sl clone https://github.com/cli/cli` and I got the same empty repo as you!

Looking at https://github.com/cli/cli, I suspect the issue is that the default branch for that repo appears to be `trunk`!

Indeed, this seems to work for me:

```
sl clone https://github.com/cli/cli --updaterev trunk
```

I suppose that, at least for GitHub repos, we could query what the default branch is via the API?

**Comment by strager** [comment]
I have the same issue with `Sapling 0.1.20221118-210929-cfbb68aa` and `Sapling 0.2.20221222-152408` (installed with Homebrew) on macOS. `sl clone git@github.com:cli/cli.git` lights up my Yubikey, and after pressing it, the command exits with a zero exit code, and I'm left with a Sapling working copy with no files checked out.

**Comment by strager** [comment]
> I suppose that, at least for GitHub repos, we could query what the default branch is via the API?

You can use the following command to query the default branch for any remote Git repo:
```shell
git ls-remote --symref git@github.com:cli/cli.git HEAD
```

**Comment by discentem** [comment]
> I suppose that, at least for GitHub repos, we could query what the default branch is via the API?

Out of my own curiosity, I'm searching around the code base to try and figure out where this API might go if added, I'm guessing somewhere in [clone()](https://github.com/facebook/sapling/blob/5f017b9a2080de77130458d7168d23a886586432/eden/scm/edenscm/git.py#L92) or [pull()](https://github.com/facebook/sapling/blob/5f017b9a2080de77130458d7168d23a886586432/eden/scm/edenscm/git.py#L316)

**Comment by discentem** [comment]
First attempt to fix, I'm sure it could use improvement! Thanks @strager for pointing out the git command for this! 

https://github.com/facebook/sapling/pull/386
