### ISSUE TITLE
Should something trigger prs to get rebased as earliers PRs in the stack get merged?

### ISSUE THREAD

**Issue by discentem** [facebook/sapling#378]
If submitted prs with `sl pr` and have the following:

PR `#1`: main <-- pr1
PR `#2`: pr1 <-- pr2

And then PR `#1` gets merged, what if anything triggers `pr2` to get retargeted to `main` instead of `pr1`? If nothing does this today automatically, could this be a feature of `sl pull` or `sl pr`? 🤔 Or perhaps a Github Bot/App?

**Comment by zzl0** [comment]
As you merge previous PRs and **delete their branches**, GitHub automatically updates the base of the next PR to the branch the previous PR was merged into (so after you merge pr1, GitHub will magically make your pr2 -> main)

**Comment by discentem** [comment]
Ah! I guess my mistake was not explicitly deleting branches. Do you know if there is a setting to automatically delete branches when merging?

**Comment by zzl0** [comment]
@discentem https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by discentem** [comment]
Thanks @zzl0!

**Comment by zzl0** [comment]
closing this, feel free to open it if you have further questions, thanks for using Sapling and reporting issues.
