### ISSUE TITLE
Github PR body gets overwritten when pushing updates

### ISSUE THREAD

**Issue by sgianelli** [facebook/sapling#430]
When working with a stack, is it expected that changes to a PR body made in Github will be overridden? Is the workflow then to add your PR description as a comment on your PR as opposed to the PR body?

**Comment by vegerot** [comment]
> When working with a stack, is it expected that changes to a PR body made in Github will be overridden?
Yes

> Is the workflow then to add your PR description as a comment on your PR as opposed to the PR body?
No.  The workflow is to put the things you would put in your PR description as the commit message body.

Note how sapling provides you with a Title, Summary, and Test Plan fields.  Make your PR Title your commit title, and your PR description as your summary

**Comment by sgianelli** [comment]
> Note how sapling provides you with a Title, Summary, and Test Plan fields. Make your PR Title your commit title, and your PR description as your summary

Where is this available? My workflow right now has been to make some change, commit it with `sl commit -m "commit message"` and then submit it with `sl pr s` which then just creates the PR immediately. I've tried `sl pr s -m "some additional message"` but that doesn't seem to do anything. Should I be submitting PRs via ISL?

**Comment by vegerot** [comment]
try `sl commit` next time 🙂 .  Ever better, I personally use `sl commit --verbose`

**Comment by vegerot** [comment]
lmk if you can't exit vim 🤡

**Comment by sgianelli** [comment]
ahh huh so that seems to work. I wonder what `sl pr s -m "message"` is doing if its not setting that commit body

**Comment by vegerot** [comment]
I don't know, and I wouldn't use that if I were you.  I would

1. `sl commit` (`--verbose`)
2. `sl pr s`
