### ISSUE TITLE
`sl --config ui.username="user" amend` does not update both author and committer

### ISSUE THREAD

**Issue by discentem** [facebook/sapling#432]
Unfortunately I still have to uncommit, recommit, relink to get this to update.

**Comment by bolinfest** [comment]
Out of curiosity, was the author already the value you specified via `--config ui.username` before amending?

And to confirm, this was with 0.2.20221222-152408-ha6a66d09 or some version of Sapling built from source thereafter? You didn't go back to the previous version or anything because of the placeholder stuff, by chance?

**Comment by discentem** [comment]
All great questions. Sorry -- I didn't ensure I was on the latest version or provide output showing the state of things with author/commiter/username. I'll update with better detail soon

**Comment by discentem** [comment]
```shell
% sl config ui.username                                    
BK <kurtz.brandon@gmail.com>
brandon@Brandons-MacBook-Pro sapling % sl amend
3c8102ab31f9 -> 2225a0fc3dea "query HEAD name, instead of assuming main/master"
brandon@Brandons-MacBook-Pro sapling % sl pr submit
pushing 1 to https://github.com/discentem/sapling
updated body for https://github.com/facebook/sapling/pull/386
brandon@Brandons-MacBook-Pro sapling % sl --config ui.username="BK <kurtz.brandon@gmail.com>" amend
2225a0fc3dea -> 3a5ee7a90aa5 "query HEAD name, instead of assuming main/master"
brandon@Brandons-MacBook-Pro sapling % sl pr submit
pushing 1 to https://github.com/discentem/sapling
updated body for https://github.com/facebook/sapling/pull/386
```

`3a5ee7a90aa5` has a different value for author and committer.

**Comment by bolinfest** [comment]
@discentem We added support for this `--config` thing for one-off fixups. Arguably the "real" fix is to do:

```
sl config --local ui.username "BK <kurtz.brandon@gmail.com>"
```

and then go back and fix up any existing commits. With the update to the local (i.e., repo-level config), all subsequent commits within that working copy should use `BK <kurtz.brandon@gmail.com>` for both author and committer.

**Comment by discentem** [comment]
Ack, I guess my expectation of `amend` is incorrect here
