### ISSUE TITLE
[proposal] sl goto top/bottom/prev/next ?

### ISSUE THREAD

**Issue by francois** [facebook/sapling#444]
I have found myself trying to run `sl goto --bottom` and `sl goto --top` a few times. I know `--bottom` and `--top` are supposed to be used with `next` and `prev`, but my fingers do the typing, not my brain.

I would argue that for consistency, having a single top-level gateway into moving the current tip would be preferable:

```
sl goto next # sl next
sl goto prev # sl prev
sl goto top # sl next --top
sl goto bottom # sl prev --bottom
sl goto $SHA1 # same as currently
sl goto $BOOKMARK # same as currently
```

I also know that currently, nothing prevents a bookmark from being named `top`, `bottom`, `next` or `prev`. Those would have to become reserved words in bookmarks.

What do you think?

**Comment by vegerot** [comment]
I too make this mistake frequently.  

FYI `top` and `bottom` are already valid revsets.

We should add a revset operator for `prev` to be `.~1` and `next` to be `.~-1`

**Comment by francois** [comment]
Oh wow! I never realized that `sl go bottom` and `sl go top` already work! This is neat! #448 is a neat alias and that's super useful. Thanks a bunch!
