### ISSUE TITLE
`sl pr submit` should not touch closed pull requests

### ISSUE THREAD

**Issue by bolinfest** [facebook/sapling#474]
This merits more investigation on my part, but I believe the way the code is written today, `sl pr submit` does not consider whether a PR is closed before trying to update it. This seems problematic and may explain some of the other issues that have been reported.

**Comment by vegerot** [comment]
Are you suggesting that sapling should open a new PR in that case?

I agree that can help work around other bugs like in #470 .

When @sTRAGER opened the PR he ran into the infamous #428 and got a Placeholder PR.  He tried closing the PR and `sl pr s`ing again but of course it just pushed to the closed PR.  Opening a new PR was the behavior he expected

**Comment by bolinfest** [comment]
`sl pr unlink` should be the recommended way to remove an association between a commit and a pull request.

**Comment by bolinfest** [comment]
Note that I think https://github.com/facebook/sapling/pull/356 will help fetch the data necessary to address this.
