### ISSUE TITLE
feature-request(pr): add Sapling version info to placeholder issue body

### ISSUE THREAD

**Issue by vegerot** [facebook/sapling#493]
idea 💡: when making placeholder issues, set the body to be the Sapling version and some info about the operation you’re doing.

If everything works, the body will be changed in a few frames and nobody notices.  If it doesn’t work, then the body will have lots of debugging information to help debug

**Comment by vegerot** [comment]
I will work on this if a maintainer tells me they would accept such patch 🙂

**Comment by vegerot** [comment]
I wish I had this when debugging #492

**Comment by muirdm** [comment]
It's a great idea that would help debugging as you point out. However, the next (current?) release disables the placeholder issue approach by default. I think we should focus effort elsewhere for now.

**Comment by muirdm** [comment]
Closing, but we should revisit if the placeholder strategy's kinks can be worked out.
