### ISSUE TITLE
`sl web`: "No such file or directory" (edenscm-isl)

### ISSUE THREAD

**Issue by mitchhentgesspotify** [facebook/sapling#521]
I'm on Fedora Linux 37

### To reproduce:

0. [`git checkout 0.2.20230124-180750-hf8cd450a`](https://github.com/facebook/sapling/releases/tag/0.2.20230124-180750-hf8cd450a)
1. `cd eden/scm`
2. `make oss`
3. `./sl web`
```
abort: No such file or directory: /home/mitch/dev/sapling/eden/scm/edenscm/commands/../../edenscm-isl/run-isl

```

[`make oss 2>&1 | tee output.txt`](https://github.com/facebook/sapling/files/10580723/output.txt)

**Comment by sggutier** [comment]
I think it should work now that https://github.com/facebook/sapling/commit/b573755c026762c69f45963359fbaf6c5a291aff got landed
