### ISSUE TITLE
How do I configure the merge conflict editor?

### ISSUE THREAD

**Issue by banool** [facebook/sapling#537]
I've searched for merge, editor, and conflict in the GH issues and searched through the docs site but I can't figure out how to configure the merge editor. Currently it opens in the XCode merge tool, I'd prefer to use VS Code / vim.

**Comment by fanzeyi** [comment]
Check `sl help config` and search for merge-tools?

https://github.com/facebook/sapling/blob/2a4d191a785083ad44c9b3938b5092c840a0af06/eden/scm/edenscm/helptext.py#L1601

**Comment by banool** [comment]
Awesome thanks :)
