### ISSUE TITLE
When update on Manjaro with `yay `, a error rose.

### ISSUE THREAD

**Issue by gnu4cn** [facebook/sapling#548]
```console
packaging.version.InvalidVersion: Invalid version: '4.4.2-20230228-205357-heb50b90a'
make: *** [Makefile:92: install-oss] Error 1
```

This error might caused by SemVer problem.

**Comment by sggutier** [comment]
Hi @gnu4cn , thanks for the report. We don't maintain the Manjaro package for Sapling, but we may be able to help.

Did you install Sapling by installing `sapling-scm-bin`, or `sapling-scm`? If it's the latter, what did `sl --version` show originally?

**Comment by gnu4cn** [comment]
> Hi @gnu4cn , thanks for the report. We don't maintain the Manjaro package for Sapling, but we may be able to help.
> 
> Did you install Sapling by installing `sapling-scm-bin`, or `sapling-scm`? If it's the latter, what did `sl --version` show originally?

I forgot whether it is `sapling-scm-bin` or `sapling-scm`. And this is the output:

```console
$ sl --version                                                    
Sapling 4.4.2
```

**Comment by gnu4cn** [comment]
But absolutely sapling-scm is ported to ArchLinux by someone as a AUR project.

**Comment by sggutier** [comment]
> Sapling 4.4.2

Ah, that might explain it. We control the version number in our packages when building by setting the `SAPLING_VERSION` environment variable, as not setting one would make the version `4.4.2`. This changed when #440 got merged, so now it shows something like `4.4.2-20230228-205357-heb50b90a` if the version is not set.

It seems that previously the `PKGBUILD` for the Sapling source file didn't include `SAPLING_VERSION`:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sapling-scm

**Comment by sggutier** [comment]
Another question: what does `python3 --version` show?

**Comment by williewillus** [comment]
@sggutier Hey, I'm packaging the AUR sapling-scm package. What should I be setting when I build the package?

**Comment by sggutier** [comment]
@williewillus 

Setting `SAPLING_VERSION` should work, so maybe you want to change the `make` line to something like

```
SAPLING_VERSION="$_realver" make PREFIX=/usr DESTDIR="$pkgdir/" install-oss
```

Also, I had to manually install `base-devel` before installing Sapling, so maybe `base-devel` should also go in `makedepends`

**Comment by sggutier** [comment]
@gnu4cn I was able to install Sapling via `yay install -S sapling-scm` on a freshly installed Manjaro 22.0. Any other steps to reproduce?

**Comment by gnu4cn** [comment]
@sggutier I'll try to run `yay` to update the installed `sapling-scm` later, to check whether this issue be fixed by @williewillus .

**Comment by gnu4cn** [comment]
Now I switched to `yay -S sapling-scm-bin` from `yay -S sapling-scm`. Successfully updated.

**Comment by williewillus** [comment]
I updated the PKGBUILD for `sapling-scm`.
