### ISSUE TITLE
Upgrading Sapling might require a restart?

### ISSUE THREAD

**Issue by SamChou19815** [facebook/sapling#550]
I understand that this might not be easy to reproduce, so feel free to close it if it's not helpful.

Today I upgraded Sapling to the latest version, and then everything breaks. I tried to uninstall and reinstall everything but it still doesn't help.

However, by reading this section (https://sapling-scm.com/docs/introduction/debugging#editing-python-code), I suspect it might be due to some long running background service being out of sync with the latest binary, so I restarted my computer, and everything works again!

If this is indeed the case, it might be good to provide some command like `sl kill` to deal with it, or even better, auto restart when it detects some version mismatch.

Some more info to help repro:

- Latest sl version: 0.2.20230228-144002-h9440b05e
- Previous sl version: 0.2.20230124-180750-hf8cd450a
- M1 Mac with macOS 13.2.1

**Comment by fanzeyi** [comment]
yeah it's the pfc server running in the background needs to be killed.

For now I just use `pkill -f start-pfc-server` to restart it. Mercurial people may have better tips.

**Comment by sggutier** [comment]
We also have `sl --kill-chg-daemon`, but the `chg` daemon should be able to automatically detect version changes

**Comment by quark-zju** [comment]
Could you provide the output of:

    CHGDEBUG=1 sl version

**Comment by SamChou19815** [comment]
Not sure whether this is helpful:

```
using chg: true, because unix
chg: debug: 0.000033 try connect to /var/folders/kh/hh85ydx53sb168s0j25yc5180000gn/T//pfc501/server-sl
chg: debug: 0.000092 start cmdserver at /var/folders/kh/hh85ydx53sb168s0j25yc5180000gn/T//pfc501/server-sl.78305
chg: debug: 0.000326 try connect to /var/folders/kh/hh85ydx53sb168s0j25yc5180000gn/T//pfc501/server-sl.78305 repeatedly
using chg: false, because CHGINTERNALMARK
chg: debug: 0.175070 connected to server-sl.78305
chg: debug: 0.175149 initialize context buffer with size 4096
chg: debug: 0.177908 hello received: capabilities: attachio chdir getencoding runcommand setenv setprocname setumask
encoding: UTF-8
pid: 78307
versionhash: 16489425442846231215
pgid: 78307
nofile: 4864 (size = 165)
chg: debug: 0.177915 capflags=0x5b03, pid=78307
chg: debug: 0.177919 request setprocname, block size 17
chg: debug: 0.177926 request attachio
chg: debug: 0.178122 response read from channel r, size 4
chg: debug: 0.178158 request chdir, block size 10
chg: debug: 0.178166 unlink /var/folders/kh/hh85ydx53sb168s0j25yc5180000gn/T//pfc501/server-sl.78305
chg: debug: 0.178223 RLIMIT_NOFILE compatible (client 4864 <= server 4864)
chg: debug: 0.178229 request setenv, block size 1368
chg: debug: 0.178486 request runcommand, block size 7
Sapling 0.2.20230228-144002
chg: debug: 0.180374 response read from channel r, size 4
chg: debug: 0.180378 got exitcode 0
chg: debug: 0.180386 free context buffer
```

**Comment by quark-zju** [comment]
> Not sure whether this is helpful:

Thanks. It is helpful.  It seems the version detection logic on chg client didn't run. If it runs you'll see something like:

    chg: debug: <timestamp> version matched (13876792458555162892)

or:

    chg: debug: <timestamp> version mismatch (client 4110897202983096134, server 13876792458555162892)

We'll investigate later.

**Comment by SamChou19815** [comment]
In the most recent upgrade, I no longer hit the assumption, so I assume it's fixed.
