### ISSUE TITLE
Sapling should interop with Jest `--watch` mode

### ISSUE THREAD

**Issue by steveluscher** [facebook/sapling#555]
The testing library Jest has [a mode](https://jestjs.io/docs/cli#--watch) where it can run tests related to changed files, according to the SCM.

I wonder if Sapling could provide some sort of reasonable ‘API compatibility’ with git by synthesizing just enough of the `.git` folder to be useful. That way tools that look for a .git folder would Just Work™ (see also https://github.com/facebook/sapling/issues/556).

# Problem

```shell
jest --watch
```

…yields the following error:

```shell
Determining test suites to run...
--watch is not supported without git/hg, please use --watchAll
```

**Comment by fanzeyi** [comment]
Do you want to open an issue in jest repo? They probably just need to recognize Sapling and they probably have Watchman support already.

**Comment by fanzeyi** [comment]
Looks like there is some basic support in Jest already: https://github.com/facebook/jest/pull/13674

**Comment by fanzeyi** [comment]
aaaaaaand I found https://github.com/facebook/jest/pull/13941

You should try updating Jest to 29.5.0.

**Comment by muirdm** [comment]
Closing assuming the above mentioned support in jest is sufficient.

**Comment by steveluscher** [comment]
And me, here, on the ancient 29.4.2. 😂

Thanks for doing my Googling for me; sorry to waste your time! :/
