### ISSUE TITLE
Sapling should interop with Turborepo

### ISSUE THREAD

**Issue by steveluscher** [facebook/sapling#556]
[Turborepo](https://turbo.build/repo) is a build system that tracks dependencies using artifact hashes. It has a fast mode that relies on SCM information which, when using Sapling, it can't find.

I wonder if Sapling could provide some sort of reasonable ‘API compatibility’ with git by synthesizing just enough of the `.git` folder to be useful. That way tools that look for a `.git` folder would Just Work™ (see also #555).

# Problem

```shell
> turbo run compile:docs compile:js compile:typedefs test:lint test:prettier test:typecheck test:unit:browser test:unit:node test:live-with-test-validator test:treeshakability:browser test:treeshakability:native test:treeshakability:node

 WARNING  cannot find a .git folder. Falling back to manual file hashing (which may be slower). If you are running this build in a pruned directory, you can ignore this message. Otherwise, please initialize a git repository in the root of your monorepo
```

**Comment by quark-zju** [comment]
We don't provide a `.git` by design. You can find some discussions at https://github.com/facebook/sapling/issues/182.

**Comment by steveluscher** [comment]
I realize that, but quitters like me who want nothing but to be able to use the Facebook/Mercurial workflow here on the outside will never be able to use Sapling unless there's an interop story with Jest/Turborepo/Codecov/etc.

**Comment by quark-zju** [comment]
I think the more realistic approach is to add sapling support in jest and turborepo (not the other way around).

**Comment by steveluscher** [comment]
Makes sense; thank you!
