### ISSUE TITLE
Can't go back to Old stacking strategy

### ISSUE THREAD

**Issue by zengk95** [facebook/sapling#558]
I noticed in https://github.com/facebook/sapling/releases/tag/0.2.20230228-144002-h9440b05e this release on this pr https://github.com/facebook/sapling/commit/a05035903a41f90ad945038d88e04c4ff4784dc4, we went back to the overlapping PRs. However I preferred the pr1<-pr2<-pr3 stacking strategy because we're not able to use review stack.

I tried doing the following and submitting, but it still just has main as my base branch. I also tried classic as well and submitting but no dice. Is there something that I'm missing? 
sl config --edit and have the following config:

```
[ui]
...
github.pr-workflow=single

```

**Comment by muirdm** [comment]
The section is `[github]`, not `[ui]`. Try `sl config --user github.pr-workflow=single`.

Sorry for the churn here. PR workflows are still a bit in flux.
