### ISSUE TITLE
Missing equivalent for `git archive`

### ISSUE THREAD

**Issue by BackSlasher** [facebook/sapling#561]
I need to create ZIP archives of my current workdir. I used to do this with `git archive`, but there seems to be no equivalent in `sl`.
I'm happy to contribute one, if this is something the team would be interested in reviewing / merging.

**Comment by quark-zju** [comment]
Is `sl archive` what you're looking for?

**Comment by BackSlasher** [comment]
Yes. I have no idea why I didn't see this earlier.
Thanks for checking :)
