### ISSUE TITLE
`sl clean --all .`, doesn't.

### ISSUE THREAD

**Issue by steveluscher** [facebook/sapling#564]
Despite this claim:

```shell
> sl githelp -- git clean -dfx .
sl clean --all .
```

Running `sl clean --all .` doesn't remove untracked-and-ignored stuff like my `node_modules/` folder.

---
Sapling 0.2.20230228-144002-h9440b05e

**Comment by steveluscher** [comment]
I see. It just doesn't remove empty dirs. OK, my feedback is that githelp should return this:

```shell
> sl githelp -- git clean -dfx .
sl clean --all --ignored --dirs .
```

**Comment by steveluscher** [comment]
Which PR would you like? The one that updates githelp's advice, or the one that changes the behaviour of `--all`?

**Comment by vegerot** [comment]
the githelp one
