### ISSUE TITLE
Feature: Allow for customization of commit template

### ISSUE THREAD

**Issue by steveluscher** [facebook/sapling#569]
1. Since Sapling is most commonly used with GitHub, the commit template should use GitHub flavored markdown by default.
    ```
    <Replace this line with a title. Use 1 line only, 67 chars or less>

    ## Summary

    ## Test Plan
    ```
2. Beyond that, my request is for a way to customize the commit template, per repository.

**Comment by steveluscher** [comment]
cc/ @discentem, @vegerot, who are working toward this in #524.

**Comment by quark-zju** [comment]
#524 is about the PR body template, not commit template. The commit template is already customizable via configuration (but PR template is not). You might want to change [this line](https://github.com/facebook/sapling/blob/69c27551a0a705d0538b2c3a85a9f49e39355892/eden/scm/lib/config/loader/src/builtin_static/sapling.rs#L505) and surrounding configs to change the default template.

**Comment by steveluscher** [comment]
Awesome! Is that documented anywhere? I looked and looked for it in the docs and couldn’t find anything.

**Comment by opsengine** [comment]
@steveluscher see related PR https://github.com/facebook/sapling/pull/1209
