### ISSUE TITLE
Overriding username setting per repository

### ISSUE THREAD

**Issue by tangentlin** [facebook/sapling#570]
### Context

I am on open-sourced contributor and also work with companies who host private GitHub repositories.  Following [Sapling's documentation](https://sapling-scm.com/docs/introduction/getting-started#setting-your-identity), I could only set a global identity which works across all repositories.

### Request

Having the ability to override the username on per repository basis help allow contributors who are on multiple repositories to make commits with the correct username.

**Comment by discentem** [comment]
Sapling user here: I think you should be able to set config options on user, repo, or global basis: 

```shell
sl config -h
sl config [OPTION]... [NAME]...

aliases: conf

...

Options:

 -u --user   edit user config, opening in editor if no args given
 -l --local  edit repository config, opening in editor if no args given
 -s --system edit system config, opening in editor if no args given

(some details hidden, use --verbose to show complete help)
```
