### ISSUE TITLE
ReviewStack not showing version 2 properly

### ISSUE THREAD

**Issue by jkeljo** [facebook/sapling#587]
https://reviewstack.dev/sdwilsh/siobrultech-protocols/pull/106

This was initially created with `sl pr submit -s`, then updated using ISL in VSCode.

ReviewStack has a couple of issues here:
1. The version dropdown shows Version 1, and the code shown is also from version 1 (version 2 had another parameter on the constructor of `PacketFormat`, which shows correctly when this PR is viewed on GitHub), but the commit hash dropdown shows the V2 commit hash.
2. The version dropdown does not show Version 2 as an option, so there's no way to get to the latest version.

<img width="1724" alt="Screenshot 2023-03-28 at 11 40 55 AM" src="https://user-images.githubusercontent.com/6788825/228336404-9bb4b72e-c5f0-4da0-a2be-b3af46685ff5.png">

**Comment by kalaracey** [comment]
I've got the same issue. v2 appears in the right hand column, but only version 1 appears in the dropdown, so the review is unreviewable in ReviewStack. It's happened to me multiple times now, I'm not sure what exactly I'm doing wrong.

**Comment by kalaracey** [comment]
Looks related to https://github.com/facebook/sapling/issues/192

**Comment by ahornby** [comment]
I'm seeing same, reviewstack versions drop down only has 1 entry despite 4 versions in sidebar and only showing the v1 changes: https://reviewstack.dev/benbrittain/buckle/pull/10       The prs are made and updated with sl pr submit using the gh backed.   Sapling version is 0.2.20230523-092610+f12b7eee,  gh version 2.31.0 (2023-06-20)

![image](https://github.com/facebook/sapling/assets/14246801/ccdf339d-3e48-4783-8dec-6ce16fc00060)

**Comment by ahornby** [comment]
published a couple of PRs that seemed to fix this for me.   reviewstack had the version related functions disabled for sapling stacks
