### ISSUE TITLE
Version string handling with setuptools 66.0.0+

### ISSUE THREAD

**Issue by ZhongRuoyu** [facebook/sapling#598]
Hi! Homebrew maintainer here. While packaging Sapling 0.2.20230330-193452-h69692651 for Homebrew at https://github.com/Homebrew/homebrew-core/pull/127884, we noticed that the build failed with this error:

```
setuptools.extern.packaging.version.InvalidVersion: Invalid version: '0.2.20230330-193452-h69692651'
```

Full logs can be found [here](https://github.com/Homebrew/homebrew-core/actions/runs/4646585831/jobs/8223122599#step:7:1454).

This was because [starting from version 66.0.0](https://setuptools.pypa.io/en/stable/history.html#v66-0-0), Python's setuptools no longer accepts version strings not conforming to [PEP 440](https://peps.python.org/pep-0440/#public-version-identifiers).

We noticed that the Sapling team are shipping their own Sapling bottles with each release. Homebrew's `setuptools` from `python@3.11` has just been bumped from 65.6.3 to 67.6.1 (in https://github.com/Homebrew/homebrew-core/pull/127641), so it is very likely that Sapling's next Homebrew bottle build will fail with the same error.

We are currently working around this error by modifying the version string as follows (see https://github.com/Homebrew/homebrew-core/pull/127884)...

```ruby
  def modified_version
    segments = version.to_s.split("-")
    "#{segments.take(2).join("-")}+#{segments.last}"
  end
```

... so that the version string `0.2.20230330-193452-h69692651` becomes `0.2.20230330-193452+h69692651`. I am filing this issue to raise some awareness about this problem. And should the Sapling team advise handling the version string differently, we can follow that. Thanks!

**Comment by zzl0** [comment]
Hi @ZhongRuoyu, thank you for reporting the issue. Yeah, we are aware of this version issue.

> ... so that the version string 0.2.20230330-193452-h69692651 becomes 0.2.20230330-193452+h69692651

This looks good to me. As long as the version contains '0.2.20230330', it should be good.

**Comment by ZhongRuoyu** [comment]
Thanks @zzl0. In that case, let me proceed to ship the new release for now.
