### ISSUE TITLE
`sl pr` strategy started submitting all new PR's against main

### ISSUE THREAD

**Issue by quuu** [facebook/sapling#599]
In the new version of sapling scm  0.2.20230228-144002-h9440b05e

I've noticed at submitting a stack, all the pr's individually would be submitted against Main

previously the nicer way of doing the review was each pr would be submitted against the parent

Submit 3 pr's: pr1, pr2, pr3

previously:

target <- branch
main <- pr1
pr1 <- pr2
pr2 <- pr3

currently:
target <- branch
main <- pr1
main <- pr2
main <- pr3

which leads to a larger diff than just what is in the branch

**Comment by zzl0** [comment]
tl;dr: you can change it back by adding below config via `sl config -e`:

```
[github]
pr-workflow=single
```

long version:

That's unfortunately a limitation of GitHub. Base must be an existing branch in the repo that has the PR (so branches in the fork wouldn't work, and refs/pull/x won't work either). If you don't have write permission in the repo there are no way to specify base to be another PR. (On the other hand, if you have write permission, writing a lot of branches just for PR base use-case seems quite noisy)
