### ISSUE TITLE
bug(phases): mark remote HEAD and all ancestors as public

### ISSUE THREAD

**Issue by vegerot** [facebook/sapling#600]
### steps to reproduce
1. `sl clone` a git repo with _many_ commits and no branches named main or master (e.g. a repo with one branch named `develop`)
2. run `sl sl`

expected: should show one commit that is the public HEAD

actual:
```sh
$ sl sl
smartlog: too many (2699) commits, not rendering all of them
(consider running 'sl doctor' to hide unrelated commits)
@    652  Mar 31 at 12:27  Max.Coplan remote/develop
... shows every commit up until the initial commit
```

note: this bug is also visible in the commit message for c8b66c68991066b3e

```
$ lhg clone --git https://github.com/cli/cli
$ cd cli
$ lhg
@  179e9c256  Yesterday at 14:13  2159081+qoega  remote/trunk
│  Add projectsV2 support to issue create, issue edit, pr create, and pr edit (#6735)
│
o    06ae07f97  Yesterday at 07:25  mislav
├─╮  Merge pull request #6880 from cli/setdefault-bare-repo
│ │
o │    351226d34  Yesterday at 07:17  mislav
├───╮  Merge pull request #6881 from cli/reviewers-json-fix
│ │ │
o │ │    241f9197e  Wednesday at 21:15  rmw
├─────╮  Merge pull request #6815 from cli/intake-doc
...
```

### Explanation

c8b66c68991066b3e added support for cloning the remote git repo's HEAD (in this case `develop`), instead of main/master by default.

However, this doesn't mark `remote/develop` and its ancestors as public commits.

### Suggested fix

When cloning a repository, mark the cloned head as public

**Comment by zzl0** [comment]
@vegerot thanks for reporting the issue. You can considering add the remote name in repo config

* This is the initial config: https://github.com/facebook/sapling/blob/c8b66c68991066b3e8731630ef757e94cd03ff36/eden/scm/edenscm/git.py#L88
* This is how we read the config: https://github.com/facebook/sapling/blob/c8b66c68991066b3e8731630ef757e94cd03ff36/eden/scm/edenscm/git.py#L327

You might need to add write logic for the repo config.

**Comment by vegerot** [comment]
@zzl0 thanks for the ideas!  What do you think of what I did in #607?

**Comment by zzl0** [comment]
@vegerot thanks for fixing it, commented in the PR
