### ISSUE TITLE
Global gitignore file isn't respected?

### ISSUE THREAD

**Issue by lazywei** [facebook/sapling#603]
Hi it seems sapling only respects the project's `.gitignore` file but not the global one `~/.config/git/gitignore`.
Is this expected and/or is there a way to do global ignore in sapling?

Thanks

**Comment by RichardCPoint** [comment]
It's hidden deep in the docs: `sl help config`

To configure Sapling to read your global gitignore file, first locate the Sapling user config file with:
```bash
sl configfile
```
then edit that file to add:
```
[ui]
ignore.userroot = ~/.gitignore
ignore.gitconfig = ~/.config/git/gitignore
```

(You can check that current config values with `sl config`.)
