### ISSUE TITLE
Revset syntax error on `.^::`

### ISSUE THREAD

**Issue by francois** [facebook/sapling#612]
According to `sl help revset`:

>     "x::y"
>      A DAG range, meaning all commits that are descendants of x and ancestors
>      of y, including x and y themselves. If the first endpoint is left out,
>      this is equivalent to "ancestors(y)", if the second is left out it is
>      equivalent to "descendants(x)".

I wanted to rebase the two topmost commits back onto master. I expected the revset `.^::` to be equivalent to "parent + self". Instead, I received a syntax error (I used log here, but I had the same error with rebase):

```
╰─○ sl log -r '.^::'
sl: parse error at 4: not a prefix: end
(.^::
     ^ here)
```

I tried to surround `::` with spaces, but I had the same syntax error. The only way not to have a syntax error was to use the revset `.^::.`.

**Comment by zzl0** [comment]
> I wanted to rebase the two topmost commits back onto master

* For your rebase use case, you can use `rebase -s .^ -d master` to achieve that.

> sl: parse error at 4: not a prefix: end

For the parser error, seems a bug in the parser, it treats `^` as infix expr and `::` as its right operand. I will dive into the issue next week.
