### ISSUE TITLE
Support for multi-root workspaces in VScode extension

### ISSUE THREAD

**Issue by equetzal** [facebook/sapling#616]
## Problem
So, currently the SmartLog extension for vscode is only usable when vscode opens the project with the `.sl` directory on the root of the workspace or only takes the first directory on a workspace. Even if this is very common for monorepos, in git is widely used the multirepos approach and within vscode is even more common to have multi root workspaces defined.

In the image you can see that the different repos are detected as sapling repos, but in fact when opening the smartlog only the first repo is shown and the others always fallback to the first one.
![image](https://user-images.githubusercontent.com/62947298/234727824-e7185519-9aed-4d20-9216-20573a6e66e6.png)

## Expected behavior
The expected result would be for the SmartLog extension to open a different tab for different repos or to have a dropbox to select the current repo, e.g. GitTree extension:
![image](https://user-images.githubusercontent.com/62947298/234728014-e4eed047-ba41-48ad-a293-5758ace1025e.png)

> Btw, Kudos to all the sapling team for this!, I was an intern at meta past summer and the tooling inside is amazing.

**Comment by evangrayk** [comment]
Thanks for filing an issue!

We added a dropdown selector to change the cwd in the stack starting at bbf9af8fe9ba86ee41dba121483e54c54d1bda96.

This should be in the next vscode extension release
