### ISSUE TITLE
Latest release is marked as a prerelease

### ISSUE THREAD

**Issue by strager** [facebook/sapling#618]
https://github.com/facebook/sapling/releases

Currently, GitHub claims that 0.2.20230330-193452-h69692651 is the latest release. The actual latest release is 0.2.20230426-145232+7ea1f245, but GitHub claims that that release is a "pre-release".

I think GitHub is confused because of the `+`, introduced in #606.

There are two problems:

* Users might be confused what the actual latest release is.
* Scripts which fetch `https://github.com/facebook/sapling/releases/latest` will download an older release, not the latest release. (This is how I found out about the issue.)

**Comment by evangrayk** [comment]
`0.2.20230426-145232+7ea1f245` is actually a pre-release, we're still in the process of finalizing our testing to make sure everything's working. After we do this, we'll mark it as the latest release and add patch notes to it. So I think things are roughly working as intended here, except that the discord bot seems to think `0.2.20230426-145232+7ea1f245` is already the latest release.

**Comment by strager** [comment]
Thank you for clarifying.
