### ISSUE TITLE
VSCode Extension - Commit details shows inverted diff

### ISSUE THREAD

**Issue by murtlatif** [facebook/sapling#634]
In the VSCode extension, when selecting `Open diff view` in the `Commit info` section, it opens the diff in the reverse order (i.e. the commit changes are the "old"/"prev" changes rather than the "current"/"new" changes.

The only exception for this is if you are currently checked out at the commit you are viewing the diff for. In this case, it looks like it presents the diff view correctly.

**Comment by RichardCPoint** [comment]
I see this too in Sapling 0.2.20230523-092610+f12b7eee.

Curiously, the diff view is correct when looking at the currently checked-out commit, but is reversed for any other commit.

**Comment by alex-statsig** [comment]
I put up https://github.com/facebook/sapling/pull/637 to fix this, just waiting on a review

**Comment by murtlatif** [comment]
> Curiously, the diff view is correct when looking at the currently checked-out commit, but is reversed for any other commit.

I do experience the same thing, and I updated the issue description as well to include this

**Comment by alex-statsig** [comment]
@sggutier (or others capable of merging in open source changes?), could review of https://github.com/facebook/sapling/pull/637 be prioritized? It's been waiting around for a month

**Comment by sggutier** [comment]
@alex-statsig sorry for the delay. I just imported your request a few minutes ago
