### ISSUE TITLE
sl pr submit fails to work

### ISSUE THREAD

**Issue by wonjae-2352** [facebook/sapling#654]
We are getting below error when we run 'sl pr submit':
failed to fetch repo id: {
 "data": {
  "repository": null
 },
 "errors": [
  {
   "type": "NOT_FOUND",
   "path": [
    "repository"
   ],
   "locations": [
    {
     "line": 3,
     "column": 3
    }
   ],
   "message": "Could not resolve to a Repository with the name '<our_repo_path>'."
  }
 ]
}

It's happening to > 5 people in the company so it may be the wide problem on Sapling. Please let us know if this is known issue or have any solution. Thanks!

**Comment by atomicharsh** [comment]
Seems to be related to: https://github.com/cli/cli/issues/7585

**Comment by zzl0** [comment]
Thank you for using Sapling! Out of curiosity, may I ask which company you are currently employed by?
