### ISSUE TITLE
sl command stops working

### ISSUE THREAD

**Issue by wonjae-2352** [facebook/sapling#655]
When this issue was ongoing (https://github.com/facebook/sapling/issues/654), I update gh and re-authenticate gh and reinstall sapling to do the sanity check. But after then, my 'sl' command stops working completely. It didn't give me the error, rather it prints nothing (same for sl log / sl list / sl status / sl pr, etc..)

![Screenshot 2023-06-16 at 8 57 25 PM](https://github.com/facebook/sapling/assets/113201882/4d8f7fe4-ea82-4413-a119-f97544d0cbfe)

I tried to uninstall and install again but have no luck so far (I use homebrew for all of these). This is on Mac M1. Appreciate any help :)

**Comment by wonjae-2352** [comment]
from emceeMC in Discord:
try sl --kill-chg-daemon && sl
or CHGDISABLE=1 sl

1st command fix my problem!

**Comment by ericclemmons** [comment]
`sl --kill-chg-daemon` fixed it for me!  Otherwise, `brew reinstall sapling` made `sl` break.
