### ISSUE TITLE
[VSCode Extension] Add blame annotations to file

### ISSUE THREAD

**Issue by murtlatif** [facebook/sapling#660]
Like gitlens has for VSCode, it'd be nice to see blame/annotations directly in vscode

**Comment by ammario** [comment]
This is done but not enabled by default. Set:

```
   "sapling.showInlineBlame": true
```

**Comment by evangrayk** [comment]
As @ammario  mentioned, this can be enabled by a vscode config setting. I wanted to get some feedback that it was working for OSS users before enabling it by default.

@ammario, re: "I had it working for a while but they disappeared for some reason. 🤷🏽‍♂️", it seems to be working for me on the latest version. You may want to check the Sapling ISL output channel in vscode (in the output tab at the  bottom, change the dropdown to "Sapling ISL"). It should have some info about when it tries to fetch blame.

**Comment by ammario** [comment]
I didn't realize Sapling had this for the first couple of weeks and was bummed out. I think it's reliable enough and important enough that it should be enabled by default.

P.s. thank you for your work on it!

**Comment by evangrayk** [comment]
Thanks for using it! I'll enable it by default for the next release.

**Comment by robhuang** [comment]
Woohoo! Yes! I'm now one tiny step closer to recreating the FB developer experience :) this is awesome thanks!
