### ISSUE TITLE
[ReviewStack] Text rendering sort of messed up

### ISSUE THREAD

**Issue by steveluscher** [facebook/sapling#668]
| ReviewStack | GitHub |
|---|---|
|![image](https://github.com/facebook/sapling/assets/13243/02dec1ae-d19d-47a4-86aa-ddfd52fe9a99)|![image](https://github.com/facebook/sapling/assets/13243/4e6071c2-866b-4e01-8a21-71ccfb95c844)|

https://github.com/solana-labs/solana-web3.js/pull/1379/commits/3f79574f68b9da032117120a135a054ffc892690
https://reviewstack.dev/solana-labs/solana-web3.js/pull/1379

**Comment by bolinfest** [comment]
I suspect https://github.com/facebook/sapling/commit/15561ab9ee08d51490ac617eb0332d804e8802b6 is the fix for this, but as noted in the commit, you likely have you log out and back in to clear IndexedDB to evict the corrupted blobs.
