### ISSUE TITLE
Where to find documentation on smartlog templates?

### ISSUE THREAD

**Issue by ammario** [facebook/sapling#685]
Sorry If I missed something obvious.

I'm having trouble finding documentation on the valid functions / variables that can be used within `sl smartlog -T {...}`.

**Comment by evangrayk** [comment]
There's help for this in `sl help templates`, hopefully that has what you're looking for

**Comment by ammario** [comment]
Thanks. That was what I was looking for. I guess I expected the web docs to be in parity with the CLI.
