### ISSUE TITLE
[ISL] [VSCode] Missing finish edit button while editing commit description/title

### ISSUE THREAD

**Issue by equetzal** [facebook/sapling#701]
## Context
When using the Interactive Smartlog, on the right panel we do have the option to edit either the Title of the commit or the Description of the PR:
<img width="1109" alt="Captura de pantalla 2023-08-09 a la(s) 8 10 37 p m" src="https://github.com/facebook/sapling/assets/62947298/9eae03fe-3bdf-4fdc-95f9-762da777b711">

## Problem
The problem is that when you click on the pencil to edit, there's no other button to save the progress or the written description. 
<img width="1110" alt="Captura de pantalla 2023-08-09 a la(s) 8 14 33 p m" src="https://github.com/facebook/sapling/assets/62947298/50aa27b0-ab5c-47c8-96f9-ee43d97845bf">
This is very problematic because even if we can edit the description in Github, if we later amend or rebase de commit and submit it again, then sapling will override the description of the PR with the regular 'title' as description, causing to dump the wrote description on Github.
This also happens with the titles, It's not being possible to save the title and then I'm needing to uncommit, re-commit with a more carefully crafted title, and then re-link the PR to the new commit to keep updating the PR with the new name.

This is happening on `v0.1.20`

**Comment by alex-statsig** [comment]
I was seeing this on `v0.1.19`, but now on `v0.1.20` I'm seeing an "Amend Message" button when I change the message but not the contents

PS: As a workaround, I was amending a small change (add a command), then removing it and amending again (rather than uncommitting which requires a new PR)

**Comment by equetzal** [comment]
> I was seeing this on `v0.1.19`, but now on `v0.1.20` I'm seeing an "Amend Message" button when I change the message but not the contents
> 
> PS: As a workaround, I was amending a small change (add a command), then removing it and amending again (rather than uncommitting which requires a new PR)

Huh, interesting. You're right, I had to remove the extension and reinstall it and how the 'Amend Message' button is also appearing. Not sure if the extension update went wrong. 
Then I'mm be closing the issue as this is now properly working. Thanks!
