### ISSUE TITLE
[ISL] Cannot use "Amend" or "Amend & Submit" (or edit messages)

### ISSUE THREAD

**Issue by alex-statsig** [facebook/sapling#709]
Amending from the ISL tree view with new changes works, but amending via the "commit panel" does not always (I have noticed sometimes it does, not sure the exact repro steps).

The option to click the title/description and enter "Edit" mode is unavailable, and clicking "Amend" or "Amend and Submit" buttons in the bottom right do nothing.

Started happening in latest version (0.1.21), guessing its related to "Propagate unsaved edited commit messages when a commit is amended"

**Comment by RichardCPoint** [comment]
I'm seeing this too. I can edit each commit's title/description once, but after the commit is amended, I can no longer edit that commit's title or description.

Closing the ISL tab and reopening it lets me edit them again (still only once per commit).

**Comment by zzl0** [comment]
Thanks for reporting the issue. I was not to reproduce it on my side.

* What's the version of you ISL?
* @RichardCPoint Are you able to reproduce it?

**Comment by evangrayk** [comment]
Thanks for reporting this, it should be fixed in 3723dfcb16f291126854994f44b701e6763b3f4b. We're publishing a new version of the vscode extension with this fix now.
