### ISSUE TITLE
VS Code blame annotations invert "(you)"

### ISSUE THREAD

**Issue by ammario** [facebook/sapling#716]
Related: https://github.com/facebook/sapling/issues/660

<img width="775" alt="Screenshot 2023-08-28 at 10 08 19 AM" src="https://github.com/facebook/sapling/assets/7416144/3327ff11-fb5b-4ff0-b46e-642b36a58924">

The VS Code extension's inline blame only shows `(you)` when I'm not the author of a commit. I skimmed the extension source and the bug isn't obvious to me.

**Comment by evangrayk** [comment]
Interesting, [the code](https://github.com/facebook/sapling/blob/9c936a5dad64ac2e949fca0562bdf8244234a088/addons/vscode/extension/blame/blame.ts#L31C1-L31C1) seems pretty simple here:
```
function areYouTheAuthor(author: string) {
  const you = getUsername();
  return author.includes(you);
}
```

You might want to check what it's detecting your username to be, perhaps it's some short string that happens to be in the other commit's author string? There is a slight mismatch between the sources of this info: "you" comes from `os.userInfo().username`, not Sapling, but the commit's author comes from Sapling / GitHub.

**Comment by ammario** [comment]
Oh! I figured it out. My username is `coder` (generic since the team uses a reproducible environment) and everyone else uses a `@coder.com` for their commits except me.
