### ISSUE TITLE
[VS Code] show author name inline in blame

### ISSUE THREAD

**Issue by ammario** [facebook/sapling#720]
See GitLens:
<img width="898" alt="Screenshot 2023-08-29 at 9 21 38 AM" src="https://github.com/facebook/sapling/assets/7416144/c55a659e-82c5-40ef-8e70-2bf40177557e">

vs. Sapling:

<img width="690" alt="Screenshot 2023-08-29 at 9 20 17 AM" src="https://github.com/facebook/sapling/assets/7416144/98dd0394-6417-4ba9-b11d-8a1bf903a47f">

who authored the commit is often more important than the commit message.

**Comment by evangrayk** [comment]
27f5af965a2d234dfc08af9ccd7448f9b77bc051 should have fixed this, I think it'll be in our next vscode extension release
