### ISSUE TITLE
[ISL] Head commit not shown in ISL if no commits branch off it

### ISSUE THREAD

**Issue by alex-statsig** [facebook/sapling#721]
If the commit checked out is on main but has no local commits branching from it, and is not the head of main, it won't show up in ISL (and thus any modified files / the "commit" button aren't shown either).
 
Steps to Reproduce:
1. Check out local main (behind remote main)
2. Make some changes, commit them
3. Pull main, so your changes are now based on an old commit of main
4. Uncommit changes

(or alternatively just manually check out a random commit on main with no local commits)

**Comment by evangrayk** [comment]
Thanks, this should have been fixed by ce42bcfacfc0f4af664dce0b110e1ee9a6b550b7
