### ISSUE TITLE
No new release since May

### ISSUE THREAD

**Issue by lazywei** [facebook/sapling#724]
Hi just wondering if it’s intended to hold off the release or it’s now recommended to just use the HEAD version of the repo?

thanks!

**Comment by zzl0** [comment]
Thanks for the issue.

> wondering if it’s intended to hold off the release

We decided that monthly release was too frequent and wanted the new release to actually include some noticeable changes. 

>  it’s now recommended to just use the HEAD version of the repo?

We are working on a new release

**Comment by sggutier** [comment]
A new release should be out now (you can mostly thank @zzl0 for that), so closing this issue
