### ISSUE TITLE
Allow viewing >25 files in ISL

### ISSUE THREAD

**Issue by alex-statsig** [facebook/sapling#727]
I really like the change to limit to 25 by default, and use a scrolling section to make large lists of files manageable. However, I can't find a way to view the rest of the files (25 at a time perhaps). This is actually a pretty common scenario with generated build artifacts (in our case, updating some graphql can affect a ton of queries and generate 25+ changed files easily)

**Comment by evangrayk** [comment]
Added pagination for this list in [6e0958c](https://github.com/facebook/sapling/commit/6e0958c3c71d21a3b4e528ff44b2ab79d2aa76a8), should be in the next vscode extension release.
