### ISSUE TITLE
`sl config --local section.name` behaves differently from `sl config section.name` (and in an unexpected way)

### ISSUE THREAD

**Issue by Flameeyes** [facebook/sapling#783]
```
$ sl config hooks.pre-commit
.sl/pre-commit/pre-commit-hook.sh
$ sl config --local hooks.pre-commit
abort: missing config value for 'hooks.pre-commit'
```

It seems like `--local` implies editing, but that is not well documented in the help message, and is surprising, particularly when compared to the `git config` equivalent.

**Comment by muirdm** [comment]
I'll try to improve the error message.

Sapling doesn't support reading config only from a particular source. If you use "--debug", it will show all the locations the value is configured (and which takes precedence).
