### ISSUE TITLE
request: open source hg-sl-up

### ISSUE THREAD

**Issue by vuduchild** [facebook/sapling#788]
Hi!
I'm really enjoying Sapling, finally feeling productive after having to deal directly with git since leaving FB.

My request - At FB internally, we used to have (and probably still have) access to a CLI utility - `hg-sl-up`, allowing to quickly change checkouts, by rendering smartlog as an interactive menu in the shell. Would it be possible to open source this tool?

Thanks!

**Comment by muirdm** [comment]
hg-sl-up uses node.js which we don't want to deal with supporting externally. We are hoping to rewrite hg-sl-up as a first class command, though, so stay tuned for that in the coming months.

**Comment by vuduchild** [comment]
@muirdm - FWIW, I've done my own quick and dirty implementation (which I bet isn't as robust as the internal one) in python. It's not a first-class command either and is in no way feature-complete, but in case people need it, here it is - https://github.com/vuduchild/sl-up.
