### ISSUE TITLE
[Feature Request] Open file / line in github

### ISSUE THREAD

**Issue by alex-statsig** [facebook/sapling#793]
The standard git vscode setup provides a context menu item on files to "Copy remote file URL", which gives a link to the file + commit from github. This is super handy for sharing code pointers with other people, especially if you want to link to a direct line. It's also a helpful segue to other features from github UI (ex. digging through blame history, etc.).

I'm not sure if this is within the scope of what the Sapling extension should do, but it feels like a gap between it and git extensions that I'm not sure how else to work around.

I'd be happy to contribute this feature if its not already being worked on, but wanted to confirm first.

**Comment by quark-zju** [comment]
It's within scope. The CodeReviewSystem is a good abstraction layer to support this (ex. a GitHub repo can support calculating URLs for GitHub). We do want to cover features provided by popular Git VSCode extensions. Right now we're busy with internal demands.

**Comment by alex-statsig** [comment]
@quark-zju Great to hear! Is this something you'd be okay with me contributing? There's probably a few decisions for how exactly to support it. I could try and get something basic up and get feedback from there.

Git extension seems to support context menu actions on lines for "Copy As > Copy Remote URL" as well as "Open on Remote (web) > Open File on Remote". The "Open on Remote" context action is also available on files (ex. in the tab header or in Explorer)

**Comment by quark-zju** [comment]
> Is this something you'd be okay with me contributing?

Definitely! I know the inline blame feature unfortunately conflicted with an internal implementation that people more familiar in this area decided to port the internal implementation instead. I don't think that's the case for the copying URL feature.

Here are some related code pointers:
- `UICodeReviewProvider`: might need a method here to convert (path, optional line), to url. You might want to make it optional so it does not break internal code review provider (which is not exported to this repo).
- `Platform.openExternalLink`: open an url.
- `Platform.openFile`: open a local file.
