### ISSUE TITLE
Feature Request: Add support for Mercurial remotes

### ISSUE THREAD

**Issue by salehqt** [facebook/sapling#796]
Please add support for cloning from a Mercurial remote:

Example:
```
sl clone https://www.mercurial-scm.org/repo/hello
```

**Comment by quark-zju** [comment]
Unfortunately, we have diverged enough from the default Mercurial configuration so supporting it is not feasible:
- Sapling requires [tree manifest](https://wiki.mercurial-scm.org/TreeManifestPlan) which Mercurial does not use by default (for compatibility reasons). Note this is a commit hash breaking change for repos that include at least one directory. It's not as simple as turning an extension on or off. 
- We have diverged from Mercurial in key concepts: See https://sapling-scm.com/docs/introduction/differences-hg and https://sapling-scm.com/docs/internals/internal-difference-hg. Sapling's current model (remote bookmarks, no named branches, remote-bookmark-decided phases, etc) are closer to Git than unconfigured Mercurial. For example, there is no way to translate Mercurial's phase information natively to Sapling, or translate Sapling's "remote bookmark" concept to unconfigured Mercurial.

Closing this as a wontfix.
