### ISSUE TITLE
Review Stack doesn't show the commit/PR stack

### ISSUE THREAD

**Issue by zcin** [facebook/sapling#826]
I have a stack of dummy PRs created through sapling:
1. https://github.com/ray-project/ray/pull/42636
2. https://github.com/ray-project/ray/pull/42635
3. https://github.com/ray-project/ray/pull/42638

However the corresponding review stack URLs don't show the "pull request X out of 3" dropdown. It only shows a "version" and commit dropdown, e.g. see [the third PR](https://reviewstack.dev/ray-project/ray/pull/42638). So I can't see the changes between PRs.
<img width="1723" alt="Screenshot 2024-01-24 at 5 01 42 PM" src="https://github.com/facebook/sapling/assets/15851518/ce9f5f10-bf13-4f4c-8fbe-46f7c9b30f5b">

On the docs it says that ReviewStack will recognize PR stacks made from sapling, I created these PRs from `sl pr submit --draft`.

Sapling version: 0.2.20240116-133042+8acecb66

**Comment by horizon-blue** [comment]
Just ran into the same issue.

I think it has to do with the `[//]: # (BEGIN SAPLING FOOTER)` textual marker introduced in https://github.com/facebook/sapling/pull/779. After removing that line manually from the PR description, Review Stack was able to correctly recognize the PR stack.

**Comment by rejc2** [comment]
Looks like it can be fixed by updating [saplingStack.ts](https://github.com/facebook/sapling/blob/55df35c00c2fd07bc89e3dc19f982bcac9917b2b/eden/contrib/reviewstack/src/saplingStack.ts).
There are already unit tests, so it should be straightforward to fix TDD-style.

**Comment by keunhong** [comment]
I took a stab at https://github.com/facebook/sapling/pull/837, but I cannot get it to build. I'm guessing it might be due to https://github.com/facebook/sapling/commit/8bc196d68985facc33badb67a3eb9372d2c61ee6.

I see the autodeployment has also been failing: https://github.com/facebook/sapling/actions/workflows/reviewstack.dev-deploy.yml

**Comment by rejc2** [comment]
> I see the autodeployment has also been failing: https://github.com/facebook/sapling/actions/workflows/reviewstack.dev-deploy.yml

Looks like this has now been fixed: https://github.com/facebook/sapling/actions/workflows/reviewstack.dev-deploy.yml
