### ISSUE TITLE
Creates invalid zip file

### ISSUE THREAD

**Issue by johnflux** [facebook/sapling#83]
https://github.com/facebookexperimental/eden/blob/694ffecfc950c381522442f20642a38666229271/eden/scm/edenscm/mercurial/archival.py#L256

This should be a 0, not a 1.  This is refering to the local-header extra fields, not the central directory

**Comment by yancouto** [comment]
I'm closing this since it's out of date. A lot has changed with the latest Sapling release, in which we now support the client on Git repos. Please reopen if you're still having issues.
