### ISSUE TITLE
VS Code Extensions Errors On Getting MergeQueue

### ISSUE THREAD

**Issue by zengk95** [facebook/sapling#830]
Hey all, we're on an older version of Github Enterprise that doesn't have merge queue yet. When using the VS Code Extension, it's trying to fetch the mergequeue fields but it's erroring out. 

![image](https://github.com/facebook/sapling/assets/34172846/e55809a9-8b4b-4126-9f13-99b0eea35e79)

Not sure if it's possible to just fetch it and have it be null or something. We're on a relatively new version (3.9) which is only about 6 months old.

**Comment by zengk95** [comment]
This isn't a blocker per se since I can still use `sl isl` but it's kind of annoying.

**Comment by alex-statsig** [comment]
This is from https://github.com/facebook/sapling/pull/718; you can downgrade the extension in the meantime to unblock too (just released in the latest version). 

To fix I think it would have to retry the query without the field, or detect the GH version and avoid querying it (I think its not that it expects it to be non-null, its that your Github doesnt have that type in its graphql schema at all)

**Comment by zengk95** [comment]
Yea, hopefully it comes out soon. I had to downgrade to 0.1.34 for anyone else having this issue.

**Comment by radsec** [comment]
++...started seeing this a few weeks ago.

**Comment by zengk95** [comment]
Think this is fixed now. Thanks @alex-statsig
