### ISSUE TITLE
Can't push to empty repository

### ISSUE THREAD

**Issue by alan-nf** [facebook/sapling#843]
I can't seem to push to an empty git repository:

```
❯ sl push -r a9bb87062 --to remote/main --force
warning: redirecting to https://my/repo.git/
fatal: bad tree object 0000000000000000000000000000000000000000
fatal: the remote end hung up unexpectedly
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
error: failed to push some refs to 'https://my/repo.git'
```

As soon as I used git to make a commit and pushed to the remote, I was able to push with Sapling.

**Comment by sggutier** [comment]
Hi @alan-nf, sorry for the delay. Can you get us more details on how to repro your issue? Is this using something else than GitHub by any chance?

Also, which Sapling version are you running? You can get that with `sl --version`

On my machine I can push to an empty repo without issues:

```
$ hg push -r 9d12e9ed1 --to remote/main --force 
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 212 bytes | 212.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/sggutier/emptything
 * [new branch]      9d12e9ed1b3daadf3aaa2faa48cb7d4a8e932157 -> main
```

**Comment by alan-nf** [comment]
Sorry for the delay:

> Is this using something else than GitHub by any chance?

Yes, Bitbucket.

FWIW I'm now on Sapling 0.2.20240219-172743+3e819974 and this works perfectly. Perhaps it got fixed since I last tried!
