### ISSUE TITLE
Sapling SCM VS Code Cannot Connect to GitHub

### ISSUE THREAD

**Issue by Tienchai** [facebook/sapling#868]
Hi - 

Thank you for working on Sapling! 

After the Sapling SCM VS Code extension release on 2024-04-04, I find that it can no longer connect to GitHub.

I am using Sapling on a few repositories that are hosted on GitHub. 
- The submit for code review button is not enabled with the tool tip that "Sumitting for code review is currently only supported for GitHub-backed repos". 
- The PRs status and link pills are no longer displayed next to the commit on the "Interactive Smartlog" tab in VS code. 
- I believe the pull button is also not shown. 

Here is my environments:
- Windows 11
- VS code version 1.88.0
- Sapling SCM VS code extension version 0.1.45
- Sapling version 0.2.20240219-172743
- gh version 2.42.1 (2024-01-16)
- git version 2.43.0.windows.1
- The repositories tested are hosted on GitHub.com (under my company's organization). 

Please let me know if you need anything else.

Thank you.

**Comment by randallb** [comment]
![CleanShot 2024-04-05 at 13 03 07](https://github.com/facebook/sapling/assets/448694/4c9f7efe-0615-41a3-beda-abbf1f0ac768)

Here's what i see in the GUI.

**Comment by randallb** [comment]
@justicart reports that it works with slweb, just not the vs code extension.

**Comment by evangrayk** [comment]
This is now fixed in the latest version on the vscode marketplace, 0.1.46!

**Comment by Tienchai** [comment]
Thank you so much for fixing! Confirm that the issue is gone in v0.1.46.
