### ISSUE TITLE
Arch and python 3.12 linking troubles

### ISSUE THREAD

**Issue by nairb774** [facebook/sapling#895]
It looks like Arch recently moved to python 3.12 which seems to be incompatible with Sapling. I've been building sapling from source, and after the upgrade, the command failed to run due to the shared libraries being swapped out. Rebuilding Sapling to use 3.11 wasn't very straight forward, and while it might be user error on my part, I figured it would be worth documenting the things I needed to do to get it working, and possibly open up a discussion around a better approach.

What eventually worked:
* Install python3.11 from at the system level [via AUR](https://aur.archlinux.org/packages/python311).
* Run: `RUSTFLAGS="-C link-args=-lpython3.11" make oss`

The use of RUSTFLAGS in this way feels fragile. There looks to be code which attempts to do version detection, maybe there is something missing somewhere?

Before playing with RUSTFLAGS at all, I tried to use pyenv to make a python 3.11 install available, but that didn't seem to work. Additionally, I tried setting up a virtualenv with the correct version of python. That also didn't work.

Log file of a failed build showing the linking errors. This log was generated with both python 3.12 and 3.11 installed at the system level.
[log.txt](https://github.com/facebook/sapling/files/15312361/log.txt)

**Comment by markbt** [comment]
Sapling uses the `rust-cpython` crate to interface with Python.  That crate hasn't had support for Python 3.12 implemented yet (see https://github.com/dgrunwald/rust-cpython/issues/294), so Python 3.12 isn't supported in Sapling either.

**Comment by nairb774** [comment]
I just rebuilt Sapling at 375f1ca0beb2d817ac6469fbf945f5c101a380b2 and it seems to build without additional config. In other words, this looks fixed but I'll leave it open for someone who knows better to say that things are working as intended.

**Comment by sggutier** [comment]
Closing this issue since this got fixed when https://github.com/dgrunwald/rust-cpython/pull/295 got merged
