### ISSUE TITLE
Sapling diff shows giant, 8-character tabs

### ISSUE THREAD

**Issue by altano** [facebook/sapling#938]
I have a .ts file that uses tabs for indentation. VS Code has defaults enabled (detect indentation from content).

When viewing this file in the editor, tabs display as 4 spaces:

<img width="683" alt="image" src="https://github.com/user-attachments/assets/a7c59e8d-e623-4a66-b1ca-1b0c99e810ee">

When viewing this file in Sapling's diff view, tabs display as a giant 8 spaces:

<img width="702" alt="image" src="https://github.com/user-attachments/assets/360ac180-0ab0-46a9-aed4-9c788dcef734">

As Fats Waller so eloquently put it: your feet's too big

**Comment by sggutier** [comment]
I think https://github.com/facebook/sapling/commit/0036a5d78cd21bf3e61f3d830123fbbc05323a82 should fix this. If it is not, feel free to reopen this issue and let us know
