### ISSUE TITLE
addons/components has some hidden deps that make it confusing to extract

### ISSUE THREAD

**Issue by bolinfest** [facebook/sapling#942]
I tried running the following script from the root of Sapling folder:

```
#!/bin/bash

# Specify the temp dir where you want to write this as output.
OUTPUT_FOLDER="$1"
mkdir -p "$OUTPUT_FOLDER"

cp -r addons/package.json "$OUTPUT_FOLDER"
cp -r addons/components "${OUTPUT_FOLDER}/components"
cp -r addons/shared "${OUTPUT_FOLDER}/shared"

cd "$OUTPUT_FOLDER/components"
yarn add --dev vite@^5.2.8
yarn add --dev '@vitejs/plugin-react@^4.2.1'
yarn add --dev 'vite-tsconfig-paths@^4.3.1'
yarn start
```

When I load the resulting http://localhost:3005/ in my browser, I get the following error in the console:

> Uncaught TypeError: stylex.inject is not a function

But when I run `yarn start` out of the Sapling checkout in the `addons/components` folder, everything works fine.

Any idea what else needs to be copied from the Sapling repo to make this work standalone?

/cc @evangrayk

**Comment by bolinfest** [comment]
Ohh, I think I may have just had to `yarn install` in `shared`, as well?

**Comment by evangrayk** [comment]
There are a few dependencies on `shared/` from `components/`, ideally we would remove those so `components/` is completely standalone. But yeah you will need to have stylex, and if you're copying components/ and shared/ but not adding them to a yarn workspace you would need to run yarn in both folders individually. In fact, we should check that both of these are declaring all their dependencies properly and not relying on anything in `addons/package.json` implicitly. That would make it easier to copy and reuse.

Separately, it would be nice if you could use the `components/` without taking the stylex dependency too, though it's useful for use to have explicit stylex support in our usage.

**Comment by bolinfest** [comment]
That said, if you look at what `components` is actually using right now...

```shell
components$ rg import *.* | grep shared | sed -n "s/.*shared\/\([^']*\)'.*/\1/p" | sort -u | sed -e 's#\(.*\)#../shared/\1\*#' | xargs -I {} sh -c 'grep import {}'
import type {FunctionComponent, PropsWithChildren} from 'react';
import {createContext, useContext, useEffect} from 'react';
import type {Json} from './typeUtils';
```

That is, it only uses `react` (which `components already depends on`) and `typeUtils.ts`, which is already required directly from `components`.

So I'm not sure why it isn't working without the second `yarn install`, or more importantly, why it fails at runtime with a strange error rather than at build time.

**Comment by bolinfest** [comment]
Again, here is another repro to try it the other way: bringing the used `shared` deps into `components` (the `sed` scripts are written for macOS):

```shell
#!/bin/bash

set -x
set -e

OUTPUT_FOLDER="$1"
mkdir -p "$OUTPUT_FOLDER"

# cp -r addons/package.json "$OUTPUT_FOLDER"
cp -r addons/components "${OUTPUT_FOLDER}/components"

# Copy on the files from shared/ that appear to be used.
mkdir "${OUTPUT_FOLDER}/components/shared"
pushd addons/components
rg import *.* | grep shared | sed -n "s/.*shared\/\([^']*\)'.*/\1/p" | sort -u | sed -e 's#\(.*\)#../shared/\1\*#' | xargs -I {} sh -c "cp {} ${OUTPUT_FOLDER}/components/shared"
popd

# Adjust the import paths to shared to make them relative.
sed -i "" -e 's#shared/#./shared/#g' "${OUTPUT_FOLDER}"/components/*.tsx
sed -i "" -e 's#shared/#./../shared/#g' "${OUTPUT_FOLDER}"/components/explorer/*.tsx

# And the import paths to isl-components.
sed -i "" -e 's#isl-components/#./#g' "${OUTPUT_FOLDER}"/components/*.tsx

# Remove `shared`` dependency from package.json
sed -i "" '/shared/d' "${OUTPUT_FOLDER}/components/package.json"

# Add the missing deps that were in addons/package.json and install and build.
cd "$OUTPUT_FOLDER/components"
yarn add --dev vite@^5.2.8
yarn add --dev '@vitejs/plugin-react@^4.2.1'
yarn add --dev 'vite-tsconfig-paths@^4.3.1'
yarn install
yarn start
```

Again, in the browser, it fails at runtime with `stylex.inject is not a function` in the console.

But if you go to `${OUTPUT_FOLDER}/components` and build the site statically, it claims to build cleanly:

```
yarn run vite build ./explorer --config vite.config.ts
```

But it doesn't actually work...

What can possibly be special about the Yarn workspace layout such that the explorer on works "in place" as it is currently written?

**Comment by evangrayk** [comment]
@bolinfest I have a stack to fix this now. First, I removed the dependency on `shared/` to simplify things. Then I added some missing dependencies for `components/`. The `stylex.inject is not a function` still persisted at that point, but upgrading `stylex` and `vite-plugin-stylex` seemed to fix that. No clue why it worked inside `addons/`.

Anyway, you should be able  to just simply copy `components/`, run `yarn` and `yarn start` and be good to go after that lands.
