### ISSUE TITLE
Documenting ecosystem

### ISSUE THREAD

**Issue by yerinu2019** [facebook/sapling#98]
Could you document about the ecosystem that can be used(or integrated) with this SCM?
Code Review tool?
Source Code Search/Navigation/Browsing/Inline edit? e.g. SourceGraph
CICD?
Bug tracking?

**Comment by yancouto** [comment]
We did a major documentation overhaul when we moved to Sapling.  We have a [website](https://sapling-scm.com/) now with a lot of docs, and clearer documentation on what's supported and what's not.
